### PR TITLE
Publish docker images for Pull Requests

### PR DESCRIPTION
**Pull request by LennyPenny**
This should make the testing of PRs easier for people that run docker setups!

### CODE REVIEW

**Comment by LennyPenny** [comment]
(the step fails because I obviously don't have access to the invidious quay.io repo)

**Comment by Perflyst** [comment]
> (the step fails because I obviously don't have access to the invidious quay.io repo)

It will fail for anyone who does not have access to this repository.
We tried this in the past, https://github.com/iv-org/invidious/commit/e35345f1358d98fa36b8d3b8b5b420260a8aef10, this does not work. Did you get this working somewhere else with some custom settings @LennyPenny?

**Comment by LennyPenny** [comment]
ah yea nvm the logic is flawed

it would be a very bad idea to let random people upload to the invidious quay account

**Comment by LennyPenny** [comment]
the only way this could work is for people that can create branched on this repo to create pull requests from

**Pull request closed without merging**
