### PR TITLE
Request next batch of recommended videos when the initial response is empty

### LINKED ISSUE #4415: [Bug] Recommended Feed No Longer Working
**Describe the bug**
The 'Recommended' list, which usually goes beside the comments on a video, is no longer shown on any instance. 

**Steps to Reproduce**
1) Open Video
2) Attempt to find additional videos to watch
3) There are no other videos to watch
4) Feel freedom for the first time ever
5) Immediately want to escape this freedom

**Logs**
No logs. 

**Screenshots**
screenshot_2024-01-31_at_00:54:56
_A LazerPig Video on Yewtu.be, showing the distinct lack of recommended videos_

screenshot_2024-01-31_at_00:58:17
_The same video on youtube.owacon.moe, showing even weird offshoots are affected by the bug_
screenshot_2024-01-31_at_01:01:57
_A different video on Yewtu.be, one that was on the Trending page and thus would likely have recommendations turned on, showing no recommended videos_
**Additional context**
This also appears to affect Newpipe, which makes me think it's a backend change - someone altered the endpoint and now every recommended feed is broken except for on Youtube.

### PR DESCRIPTION
**Pull request by syeopite**
Based on @absidue's findings on Matrix https://matrix.to/#/!yAXokUArOJxHEACeib:pussthecat.org/$wztvNd98iLTXIsqmBjP57BhCrV5Z9bjgj01CElwEtBE?via=nitro.chat&via=matrix.org&via=tchncs.de

This PR fixes recommended videos by requesting the next batch when the initial response is empty.  Do note however that YouTube will occasionally just not return anything all and as such recommend videos are still broken in those cases. 

Make sure to clear the video cache when testing this PR!

Closes #4415

### CODE REVIEW

**Comment by ggtylerr** [comment]
Have this fork [up and running on my instance](https://iv.ggtyler.dev) - looks like it doesn't work for most MVs. [Now and Then (audio-only)](https://iv.ggtyler.dev/watch?v=AW55J2zE3N4) works [but not the music video.](https://iv.ggtyler.dev/watch?v=Opxhh9Oh3rg) Same goes for [Around the World](https://iv.ggtyler.dev/watch?v=K0HSD_i2DvA), [Robot Rock](https://iv.ggtyler.dev/watch?v=sFZjqVnWBhc), and [Lagtrain.](https://iv.ggtyler.dev/watch?v=UnIhRpIT7nc)

Interestingly enough, not all MVs seem to be affected by this, such as [Giga - ガッチュー！](https://iv.ggtyler.dev/watch?v=oEkGC2HV7rc) and [Giga - Beyond the way.](https://iv.ggtyler.dev/watch?v=SJcgOWsDwi4)

*(thank you [Ashley](https://ashley0143.xyz/) for letting me know about this and for providing a couple of the examples)*

**Comment by absidue** [comment]
@ggtylerr Those videos don't have any recommended videos on YouTube itself, so Invidious cannot show them either, I did explain that to Ashley in the Invidious Matrix room but she didn't really listen.

**Comment by ashley0143** [comment]
oh i see - thanks. @absidue

**Comment by ggtylerr** [comment]
> @ggtylerr Those videos don't have any recommended videos on YouTube itself, so Invidious cannot show them either, I did explain that to Ashley in the Invidious Matrix room but she didn't really listen.

It looks like they do on my end, but maybe this is YT rollout making it inconsistent?
Screenshot of Around the World's MV on Invidious
Screenshot of Around the World's MV on YouTube

**Comment by absidue** [comment]
The whole thing is very inconsistent but when it's missing on Invidious with this pull request, it means that the response that it got from YouTube was blank (the property that usually contains the watch next list is missing entirely), you can intercept the traffic between your instance and YouTube if you don't believe me.

Just for the record I cannot see recommended videos on youtube.com for those videos on my end.

**Comment by ashley0143** [comment]
seems as youtube fixed the bug - idk if this pr should be merged tho

**Comment by ashley0143** [comment]
i think it should still be merged if youtube screws it up again lol

**Pull request closed without merging**
