### PR TITLE
API: Add endpoint to resolve youtube urls

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
Added to misc endpoint as it resolves more than just channel urls

### CODE REVIEW

**Review by SamantazFox — APPROVED** [review]

**Comment by absidue** [comment]
Would probably be a good idea to return the page type in the response too. That way people know which other API endpoint to pass the returned ID to.

**Review by SamantazFox — APPROVED** [review]
Looks good to me!

**Comment by absidue** [comment]
Sorry if I was holding this pull request up, looks good to me too!

**Comment by SamantazFox** [comment]
> Sorry if I was holding this pull request up, looks good to me too!

Don't worry, It's only me being quite busy lately ^^

**Comment by SamantazFox** [comment]
@ChunkyProgrammer  Thanks for your contribution :D

**Pull request merged**
