### PR TITLE
Multiple search fixes

### LINKED ISSUE #2140: [Bug] Incorrect search behavior if the query contains non-English letters or words.
**Describe the bug**
When trying to do a video search, if the query contains non-English letters or words, the search instead of what I entered in the query returns garbage in the search results.
And this is the case with all queries that contain non-English letters or words, which makes it almost impossible to use the search.
What's strange is that not all instances are affected by this problem, but only a certain part of them.
Attempts to experiment with the search filter parameters did not help either, the search results are still garbage.

Instances that are affected by this issue:
invidious.snopyta.org
yewtu.be
invidious.silkky.cloud

Instances that are not affected by this issue:
invidious.048596.xyz
inv.riverside.rocks

**Steps to Reproduce**
Try to enter a search, for example "Фильмы ужасов".

**Expected behavior:**
In the search results should appear videos, one way or another related to the horror genre.

**Actual behavior:**
The search results return "garbage" videos that have absolutely nothing to do with the horror genre.

**Screenshots**
Screenshot 1 which was taken on the instance yewtu.be is affected by this issue and is the actual behavior.
test
Screenshot 2 which was taken on the instance inv.riverside.rocks is not affected by this issue and is the expected behavior.
test2
**Additional context**
 - Browser: Firefox ESR 78.11.
 - OS: Windows 10.

### PR DESCRIPTION
**Pull request by SamantazFox**
Fixes #2140 

Other fixes:
* Empty search redirects to /search, not /
* Show the fullscreen search "home page" (from #1977) at /search
* Allow 'region=' parameter to be passed to /search
* Add "search" to fullscreen search page's `<title>`

### CODE REVIEW

**Comment by hackerncoder** [comment]
Is https://test.invidious.io/ supposed to run this entire PR or only some of it, since /search doesn't seem to work on it.

**Comment by SamantazFox** [comment]
> Is https://test.invidious.io/ supposed to run this entire PR or only some of it, since /search doesn't seem to work on it.

it runs this entire PR.

**Comment by SamantazFox** [comment]
Ah, yeah /search broke here too. So weird... I'll try something.

**Comment by SamantazFox** [comment]
That linter is driwing me crazy D:

<details>
<summary>Build Failed - Lint step logs</summary>

```
Run if ! crystal tool format --check; then
formatting './src/invidious/routes/search.cr' produced changes
Format ./src/invidious/routes/search.cr
```
```patch
diff --git a/src/invidious/routes/search.cr b/src/invidious/routes/search.cr
index 859487e..513904b 100644
--- a/src/invidious/routes/search.cr
+++ b/src/invidious/routes/search.cr
@@ -45,7 +45,6 @@ class Invidious::Routes::Search < Invidious::Routes::BaseRoute
       # Display the full page search box implemented in #1977
       env.set "search", ""
       templated "search_homepage", navbar_search: false
-
     else
       page = env.params.query["page"]?.try &.to_i?
       page ||= 1
```
`Error: Process completed with exit code 1.`
</details>

**Comment by SamantazFox** [comment]
> Is https://test.invidious.io/ supposed to run this entire PR or only some of it, since /search doesn't seem to work on it.

My last commit fixed it :)

**Review by syeopite — APPROVED** [review]

**Review by unixfox — APPROVED** [review]

**Comment by TheFrenchGhosty** [comment]
Thank you.

Thank you for testing @Mennaruuk @noname946

**Pull request merged**
