### PR TITLE
Provide rough draft of better project organization

### PR DESCRIPTION
**Pull request by matthewmcgarvey**
Hi 👋  I've not used invidious much, but I'm seeing a lot of comments talking about the project being in need of more crystal devs. As a crystal dev, I feel like I can pitch in a bit. https://github.com/iv-org/invidious/issues/1352, https://github.com/iv-org/invidious/issues/1350, https://github.com/iv-org/invidious/issues/1361

As https://github.com/iv-org/invidious/issues/1121 pointed out, everything being in a single file and global is quite difficult to work with. Before making a huge leap to a new framework, though, I think the best thing to do is to organize everything just a bit. This PR adds two new patterns that I hope will help wrangle the code.

1. I've added an `Invidious::Routes` module that serves as controllers along with an `Invidious::Routing` module for the route macros. It's definitely not the best thing in the world but I can hope you see it going in the right direction.
2. I've also added an `Invidious::Jobs` module that can wrap all the async jobs being performed so that we can move away from global methods

I would hope that once these patterns are worked into Invidious that it might make the transition to a framework like [Grip](https://github.com/grip-framework/grip) or even [Lucky](https://luckyframework.org/) manageable.

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
Amazing, is this PR finished? Can we assume everything will be working with it?

**Comment by matthewmcgarvey** [comment]
@TheFrenchGhosty this PR can be considered finished and if it gets merged I can update the rest of the code. I did verify it worked locally

**Comment by TheFrenchGhosty** [comment]
We are currently testing this PR. If everything is working we will merge it soon.

Thanks again.

**Comment by Perflyst** [comment]
No issues so far, thank you!

**Comment by SamantazFox** [comment]
> I would hope that once these patterns are worked into Invidious that it might make the transition to a framework like [Grip](https://github.com/grip-framework/grip) or even [Lucky](https://luckyframework.org/) manageable.

I see a lot of "REST" and "RESTful" on the pages you liked.
I'm a bit worried because this often means "a lot of javascript on the client". Is this your idea?

I appreciate a lot the fact that invidius runs super fine without javascript, so loosing that would be loosing its core idea.

**Comment by matthewmcgarvey** [comment]
@SamantazFox I have no intention of moving towards a heavy javascript implementation so I think we're on the same page 😄. I provided those links just as a goal of moving this project to have a better structure than we have right now.

**Comment by grkek** [comment]
@SamantazFox In Grip you can use the same rendering engine Kemal uses to avoid the JavaScript hell.

**Pull request merged**
