### PR TITLE
ci: update github actions

### PR DESCRIPTION
**Pull request by armujahid**

### CODE REVIEW

**Review by SamantazFox — APPROVED** [review]

**Comment by unixfox** [comment]
@armujahid 

ideally it would have been so cool if you could update the version of all the other actions :). that would save us a lot of time

**Comment by armujahid** [comment]
Sure. Will check

**Comment by armujahid** [comment]
@ unixfox  done

**Comment by unixfox** [comment]
@armujahid did you check that all the tags exist because there is an error at the compilation: https://github.com/iv-org/invidious/actions/runs/6884034885/job/19054420702?pr=4209

**Comment by armujahid** [comment]
@unixfox  I have reverted my change related to install-crystal. it should pass now.

**Pull request merged**
