### PR TITLE
Set channel thumbnail as icon for feeds

### LINKED ISSUE #1064: Suggestion: set icon element to channel logo on atom feeds
When you have a large number of invidious feeds in your feed reader (I personally have over 30) it quickly becomes unmanageable when they all have the same icon. Setting the [icon tag](https://tools.ietf.org/html/rfc4287#section-4.2.5) to the channel logo whenever possible would help with this.

### PR DESCRIPTION
**Pull request by agraven**
Should close #1064.

### CODE REVIEW

**Comment by omarroth** [comment]
Thanks! Unfortunately I'm having trouble getting this to work. I've tried a couple similar changes but all the readers I've tested will default to `/favicon.ico` and not check `icon` or `logo`. I've tested [akregator](https://userbase.kde.org/Akregator), [tt-rss](https://tt-rss.org/), [quiterss](https://quiterss.org/), and [liferea](https://lzone.de/liferea/).

I've read through the mentioned [RFC](https://tools.ietf.org/html/rfc4287) but there doesn't appear to be much information on this. Is there some specific format required by RSS readers?

**Comment by leonklingele** [comment]
I've dealt with this before. Although written in [RFC 4287](https://tools.ietf.org/html/rfc4287#section-4.2.5), none of the feed readers I tested looks up and follows the `atom:icon` element. They only ever seem to request `favicon.ico`, check the [code from NewsBlur](https://github.com/samuelclay/NewsBlur/blob/ff4eac73bb7f4c8ea1078818f7a77f9e32e56054/apps/rss_feeds/icon_importer.py) as an example.
This could be merged for readers who follow RFC 4287, but it probably won't fix your issue @agraven. Which service are you using btw?
There might be other solutions such as including `<link rel="shortcut icon" href="#{xml.text channel.author_thumbnail}" />` on the channel overview page (HTML), and adding that page to your feed reader in the hope it will retrieve the custom favicon from there.

**Comment by agraven** [comment]
Definitely worth experimenting with, I'll look into it.

Oh, and I'm using TinyTinyRSS with liferea as client

**Comment by leonklingele** [comment]
> I'm using TinyTinyRSS

Well, then the solution mentioned above (`<link rel..` on the channel HTML page) should work for you! https://git.tt-rss.org/fox/tt-rss/src/44b1f0fcc0a0497b8fa0895b8655f4f1b9396ace/classes/rssutils.php#L1700

@omarroth what do you think of merging this + using the YT channel's thumbnail as a favicon on channel overview pages? Every Invidious channel page will then have it's own bookmark icon. Some readers probably support none of the two solutions but I suppose it's the best we can do.

**Comment by omarroth** [comment]
Sounds good to me.

**Comment by agraven** [comment]
Should this be merged as is or should I add code for the link tag in channel pages as well?

**Comment by Rjevski** [comment]
@TheFrenchGhosty could we merge this? I've had this working successfully for over a month on my personal instance using News Explorer as the RSS client.

**Review by saltycrys — APPROVED** [review]

**Comment by Perflyst** [comment]
I guess we can merge this but I will keep https://github.com/iv-org/invidious/issues/1064 open so that the suggestion mentioned in https://github.com/iv-org/invidious/pull/1106#issuecomment-611932035 for other readers could be implemented too

**Pull request merged**
