### PR TITLE
Update hu-HU.json

### PR DESCRIPTION
**Pull request by f3rr31**
07-JAN-2022 update. Fixed malformed `x` string at line 339 and corrected translation inconsistencies.

### CODE REVIEW

**Comment by unixfox** [comment]
Not sure, but I think you need to submit the translations on https://hosted.weblate.org/engage/invidious/ instead.

@SamantazFox correct?

**Comment by SamantazFox** [comment]
> @SamantazFox correct?

Yep! Otherwise, this will collide with the current changes: https://github.com/iv-org/invidious/pull/2769

**Comment by SamantazFox** [comment]
@f3rr31 Oh, I see you already made the changes on Weblate! There are a few merge conflicts to solve, that's why the Weblate PR is pending.

**Comment by f3rr31** [comment]
Thank you all Foxen for cross-checking and looking into it! this PR's hu-HU.json was exported via Weblate.

**Comment by SamantazFox** [comment]
Btw, regarding the hungarian translations, I saw that you updated the following (among others):
```
`x` view"  => "`x` már látta"
`x` views" => "`x` már látta"
```

I know that [hungarian has two plural forms](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#hu) (singular if a count is "one", and plural otherwise, same as in english). Is there a reason why the two strings are identical?

(If you wonder, I'm simply trying to understand ^^. I've worked on a PR that will improve the quality of translations when plurals are encountered)

**Comment by f3rr31** [comment]
Sure, thanks for asking it. If you have more to ask, feel free to! Hope this answers your question:

**For views:**
_“\`x\` view“_  → **„\`x\` már látta”**
_“\`x\` views“_ → **„\`x\` már látta”**

**_[Text between brackets can be omitted and it is written to show examples of complete sentences.]_**
I went for translating Hungarian literally (word by word) to English in order to represent word order and grammar more precisely.

**I tried to keep it brief and “natural-sounding“ by traslating it to:**
_“123 [human] already saw [the video]“_ → **„123 [ember] már látta [a videót]”**

**Noun plurals are always singular and never plural, thus:**
**_<#number> can be any number; it does not matter if it is 1 or 256 or a huge number._**
**„0 [ember] látta“** sounds nerdy and it should be **„Senki sem látta még [a videót].”** → _“No-one neither saw yet [the video].“_

_“<#number> [human] already saw [the video].“_ → **„<#number> [ember] már látta [a videót].”**_—🗸_
_“<#number> [humans] already seen [the video].“_ → **„<#number> [emberek] már látták [a videót].”**_—✘_
_“<#number> [human] already seen [the video].“_ → **„<#number> [ember] már látták [a videót].”**_—is even more wrong since there is a mismatch of humans and the plural of **látta [látták].**_

**For curiosity’s sake:**
_“[they] have already seen [the video].“_ → **„[ők] már látták [a videót].”**_—🗸_

I tried to overcome that 16–17 character limit where there _“\`x\` views“_ strings are, so first, I translated this as _“32K occasion they seen“_ → **„32K alkalommal nézték meg”** but being verbose resulted in text overflow (see any recently updated IV-instance set to Hungarian to see how broken I managed to get it _x.x_).

**Some more examples:**
_“\`x\` unseen notification“_  → **„\`x\` kimaradt értesítés”**_—🗸_
_“\`x\` unseen notifications“_ → **„\`x\` kimaradt értesítések”**_—✘_
Same thing as above; noun plurals are always singular.

_“Only the unseen notifications we read[past].“_ → **„Csak a kimaradt értesítéseket olvastuk el.”** _(We only read the unseen notifications. [Emphasis is on unseens and not any others.])_—🗸

That Language Plural Rules link is interesting (thanks!) but strictly speaking **„megveszi őket”** is incorrect unless you are speaking about animals you are about to buy of which you are fond of. **Őket** is _them_ and you use it for humans/people: _“I know them.“_ → **„Ismerem őket.”**

Same stuff for time e.g. year/month/day/hour as in _“6 minute since I missed the flight.“_ → **„6 perce késtem le a repülőt.”** _(I missed the flight 6 minutes ago.)_

<details><summary>Just food for thoughts about plural formatting◃</summary>
<p>

What I wanted to mention is in English:
```%A %B %-d, %Y```
 ```Shared Jan 7, 2022```
 
 In Hungarian:
  ```%Y. %B %-d %A```
 ```2022. január 7 napon osztották meg```_—✘_
```2022. január 7-ei napon osztották meg```_—🗸_
 
| Abbreviated English | What this plurals PR could be beneficial for is ordinal dates:   | Abbreviated Hungarian | 
| :-: | :-: | :-: |
| 1st of → | elsején → | 1-én|
| 2nd of → | másodikán → | 2-án| 
| 3rd of → | harmadikán → | 3-án|
| 4th of → | negyedikén → | 4-én|
| 5th of → | ötödikén → | 5-én|
| 6th of → | hatodikán → | 6-án| 
| 7th of → | hetedikén → | 7-én|
| 8th of → | nyolcadikán → | 8-án| 
| 9th of → | kilencedikén → | 9-én|
| 10th of → | tizedikén → | 10-én|
| 20th of → | huszadikán → | 20-án|
| 31st of → | harmincegyedikén → | 31-én | 

| Abbreviated English | We don’t use these that often:  |  Abbreviated Hungarian |
| :-: | :-: | :-: |
| 100th of → | századikán → | 100-án |
| 1,000th of → | ezredikén → | 1000-én |
| 100,000th of → | százezredikén → | 100 000-én |
| 1,000,000th of → | milliomodikán → | 1 000 000-án |
| 1,000,000,000th of → | milliárdodikán → | 1 000 000 000-án |
</p>
</details>

**Unrelated:**
_“The video“_ denotes a specific video what people are discussing in context and not any other video. _“That video“_ would be literally **„azt a videót”** and you say that when you are having a conversation about a video what is (spatially) far from you and both from who you are speaking to.


It can be _“this video“_ as in **„ezt a videót”** like when you are watching a video on your phone and you start to show it to someone else asking **„Láttad már ezt [a videót]?“** → _“You seen already this [video]?“_

**Comment by SamantazFox** [comment]
@f3rr31 Wow! Thanks a lot for this explanation :D

> **I tried to keep it brief and “natural-sounding“ by traslating it to:**
> _“123 [human] already saw [the video]“_ → **„123 [ember] már látta [a videót]”**

Ah, I see. Would you translate differently if it was `watched X times`? (In essence, keeping the sentence quite impersonal and outside a phrase context).

> I tried to overcome that 16–17 character limit where there _“`x` views“_ strings are, so first, I translated this as _“32K occasion they seen“_ → **„32K alkalommal nézték meg”** but being verbose resulted in text overflow (see any recently updated IV-instance set to Hungarian to see how broken I managed to get it _x.x_).

Yes, that's why translating in not always easy! There are quite often space constraints, and many languages are much more verbose than english (we have the same problem in french ^^).

> **Some more examples:**
> _“\`x\` unseen notification“_ → **„\`x\` kimaradt értesítés”**_—🗸_
> _“\`x\` unseen notifications“_ → **„\`x\` kimaradt értesítések”**_—✘_
> Same thing as above; noun plurals are always singular.
> 
> _“Only the unseen notifications we read[past].“_ → **„Csak a kimaradt értesítéseket olvastuk el.”** _(We only read the unseen notifications. [Emphasis is on unseens and not any others.])_—🗸

That's very interesting!

> That Language Plural Rules link is interesting (thanks!) but strictly speaking **„megveszi őket”** is incorrect unless you are speaking about animals you are about to buy of which you are fond of. **Őket** is _them_ and you use it for humans/people: _“I know them.“_ → **„Ismerem őket.”**

This is from [Unicode's Common Locale Data Repository (CLDR)](https://en.wikipedia.org/wiki/Common_Locale_Data_Repository). Probably the "gold standard" in terms of internationalization.

The idea behind these plural rules is to cover all of the plural variations of a language, even though in some contexts (as you mentioned it), the same translation is used for different variants.

> What I wanted to mention is in English:
> `%A %B %-d, %Y`
> `Shared Jan 7, 2022`
> 
> In Hungarian:
>`%Y. %B %-d %A`
> `2022. január 7 napon osztották meg`_—✘_
> `2022. január 7-ei napon osztották meg`_—🗸_

Regarding that part, I'm aware that the date formatting is completely off of tracks.

We're currently using _Crystal_'s standard library, which only supports english. @syeopite has been working on [a CLDR library for the crystal language (called lens)](https://github.com/syeopite/lens) which will add suitable number and date formatting, amongst other internationalization features.

In the meantime, I think that it'd be better if we used ISO dates & times (`YYYY-mm-dd` optionally followed by  `HH:MM`).

**Pull request closed without merging**
