### PR TITLE
Add support for the new channel layout (part 1)

### LINKED ISSUE #3371: [Bug] List of videos on a channel page is incorrect - no pagination channel
Summarized by @unixfox: 

The list of videos on a channel page is incorrect, sometimes it returns all the correct videos, sometimes nothing or other times only old videos.

Related issue: https://github.com/TeamNewPipe/NewPipe/issues/9223

-----

Lately, since a week or so i'm having a wired issue that never happened before.
Say for example i'm opening my browser and connecting to https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q
The channel either show old content like couple of months ago, or it does not load any content at all, and sometimes it loads the latest content as expected, why does this happen?

First screenshot there are supposed to be videos between the channel name and the susbscribe button but there are none.
Second screenshot shows videos from a month ago not the latest one, i had to reload the page like four times like gabling to get it load the latest videos.

### PR DESCRIPTION
**Pull request by SamantazFox**
Closes #3371

### CODE REVIEW

**Comment by unixfox** [comment]
Interesting findings: https://www.reddit.com/r/NewPipe/comments/yie0ca/workarounds_for_the_new_youtube_channel_tabs/

**Comment by SamantazFox** [comment]
Current state of the PR: channel videos are back, but paging is still broken.

**Comment by schleussinger** [comment]
[46a63e6] works on my instance as described (Channel list is present, paging always returns page 1). Thanks!

**Comment by sonicrules1234** [comment]
Livestreams (both live and archived) are still missing from the channel pages

**Comment by SamantazFox** [comment]
> Livestreams (both live and archived) are still missing from the channel pages

This will be addressed in the future ^^
For now, I'd like to have at least the channel videos back up.

**Comment by SamantazFox** [comment]
poke @unixfox: I think we should merge this PR as-is to at least provide the latest videos of a channel.
It's not perfect (continuations are still broken), but would at least help with #3371

**Review by unixfox — APPROVED** [review]

**Comment by unixfox** [comment]
Ever tried to see if the pagination is easier on clients like MWEB or ANDROID?

**Comment by SamantazFox** [comment]
> Ever tried to see if the pagination is easier on clients like MWEB or ANDROID?

Nope, thanks for the idea! (Though I'm pretty sure it won't work on android, given recent exchanges with TiA4f8R over on matrix)

**Pull request merged**
