### PR TITLE
User code cleaning & fixing

### PR DESCRIPTION
**Pull request by SamantazFox**
Clean code related to the different user systems (imports/export, cookies, captcha, login):

* Move the last user routes (account related) out of `invidious.cr`
* Move the base `User` struct to its own file & under the `Invidious` namespace
* Move (registration) captcha code to their own module & file
* Split user data import logic to separate functions, and put that under a separate module/file
* Deduplicate and simplify cookies code
* Move user ECR template files to their own folder

Note 1: this is a preliminary work towards a large rework of the user backend.

Note 2 (for @matthewmcgarvey): Commits can be reviewed independently (so, while some commits depend on one another, the code should always compile, and no "module" should be changed by two different commits).

### CODE REVIEW

**Comment by SamantazFox** [comment]
(Don't mind the two force-pushes, I forgot to put the module name in the spec after movind the CSV function there).

**Review by matthewmcgarvey — APPROVED** [review]

**Comment by SamantazFox** [comment]
Deployed on https://test.invidious.io

**Comment by SamantazFox** [comment]
Working so far:
[x] Account creation
[x] Login / logout
[x] Account deletion
[x] change password
[x] Clear watch history
[x] Export as JSON

**Review by matthewmcgarvey — APPROVED** [review]

**Comment by SamantazFox** [comment]
Ok, I finally finished testing all the features. Everything is working, now.
@matthewmcgarvey I added a single commit to fix import from FreeTube, can you look at it?

**Review by matthewmcgarvey — APPROVED** [review]

**Pull request merged**
