### PR TITLE
Bump kemal dependency to v1.1.2

### PR DESCRIPTION
**Pull request by SamantazFox**
Supersedes #2921
Closes: https://github.com/iv-org/invidious/issues/2783

Solve broken playback on crystal 1.3.*
See: https://github.com/kemalcr/kemal/pull/628

### CODE REVIEW

**Review by matthewmcgarvey — APPROVED** [review]

**Comment by unixfox** [comment]
Is this PR deployed on test.invidious.io :)?

**Comment by SamantazFox** [comment]
@unixfox yep, and Idk why it doesn't work :/

**Comment by unixfox** [comment]
Still not working?

**Comment by SamantazFox** [comment]
@unixfox yep, there is still an issue.

**Pull request merged**
