### PR TITLE
Add awesome-humane-tech badge

### LINKED ISSUE #1331: You were added to awesome-humane-tech
This is just a FYI issue to notify that you were added to the curated awesome-humane-tech in the 'Social media' category, and - if you like that - are now entitled to wear our badge:

[Awesome Humane Tech](https://github.com/humanetech-community/awesome-humane-tech)

By adding this to the README:

```markdown
[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)
```

https://github.com/humanetech-community/awesome-humane-tech

### PR DESCRIPTION
**Pull request by hackerncoder**
Fix #1331.

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
@saltycrys @Perflyst if you are okay with that approve this PR, otherwise don't.

I don't personally care.

**Review by TheFrenchGhosty — APPROVED** [review]

**Comment by Perflyst** [comment]
I ask myself why the original issue has 5 downvotes

**Comment by TheFrenchGhosty** [comment]
@Perflyst From what I know some people don't like awesome-humane-tech... I don't know why though.

**Review by saltycrys — COMMENTED** [review]
I don't have an opinion on this.

**Comment by jksladjflkjsadflkjsadf** [comment]
Personally, I think it is better to do whatever is better for getting interest in the project, which I'm not sure either way what that badge would do.

But for reasons of opposition, I could think of the possibilities:

1. The humane tech community does not seem to be very active, and this badge would be alot more beneficial to them and not for the iv project.
2. The humane tech project may be politically aligned and association with their project may not be desired by the iv project.

**Comment by hackerncoder** [comment]
1. Sure. But it would also be beneficial to users, who can find more alternatives or good projects to use.
2. I won't argue with that. If it is true I will close this PR.

**Comment by jksladjflkjsadflkjsadf** [comment]
I'm just giving ideas to consider.  I personally don't support or oppose this directly.

**Comment by Perflyst** [comment]
I heard and also (verified)[https://www.humanetech.com/who-we-are] that some of the humantech people are ex big tech employees which is one reason why some others don't like the humantech thing. The badge does not change the software Invidious in any way and since there are quite different opinions in the community (see downvotes) I will close this PR.

However, this does not mean that Invidious directly supports or opposes it.

**Comment by aschrijver** [comment]
@Perflyst I feel I must follow up on this. The Humane Tech Community is fully independent of Center for Humane Technology. I started the grassroots community as a volunteer, using their forum when they had no time for community building. Other than that we have our own website at htts://humanetech.community

**Pull request closed without merging**
