### PR TITLE
Make invidious use HTML5 innertube client if the Android client fails

### PR DESCRIPTION
**Pull request by techmetx11**
This makes Invidious fallback on the HTML5 client if fetching the streaming data from Android fails.
Fixes the current issue with YouTube returning a "Video Not Available" video on the outdated Android client version that Invidious uses (also makes the code log a warning in case this happens too)

### CODE REVIEW

**Comment by SamantazFox** [comment]
The problem with WEB/TV clients is that the streams are throttled.
To fix that, we'd have to implement a JS sandbox for the n-function.

It's good as a temporary fix for a small instance, but it can't scale for public instances.

**Comment by SamantazFox** [comment]
Still, thanks for the PR ^^

**Comment by unixfox** [comment]
I still think we should fallback to WEB even if we are throttled.

It is better to provide a video feed than having an error.

**Comment by SamantazFox** [comment]
I don't know. I thing it's more frustrating to have a video that takes forver to load than a straight out error.

I'm really reconsidering adding some JS parser for the n-function.

**Comment by raxod502** [comment]
Even if the JS parser isn't added, it might be warranted to allow server administrators to enable fallback to HTML5 streaming. After all, some servers are intended for personal or small-group use, and the tradeoff might be considered superior in those cases. The administrator of the server in question would be best positioned to make that determination, hence my suggestion that this might make sense as a server-side config option.

**Pull request closed without merging**
