### PR TITLE
Bump videojs and fix webworker

### LINKED ISSUE #1707: Captions without any Captions
Yes, it's a strange thing and seems to affect the two instances I've tested.
https://invidious.kavin.rocks/api/v1/captions/w3j3tivcm50?label=English%20(auto-generated)&hl=en-US
https://invidious.snopyta.org/api/v1/captions/w3j3tivcm50?label=English%20(auto-generated)&hl=en-US

On YouTube, the captions work as expected: https://www.youtube.com/watch?v=w3j3tivcm50

This is not related to #1703 as that contains an error and this doesn't.

### PR DESCRIPTION
**Pull request by tenpura-shrimp**
This change bumps the videojs to the latest stable version.  The current videojs requires real webworkers for hls and dash.  I updated the CSP so that this will work.  Safari does not support worker-src CSP, so I updated the child-src CSP.

This is a prerequisite, but does not fix or affect #1707 and #1703

Tested livestream and dash playback on safari, chrome, and firefox.

### CODE REVIEW

**Comment by hackerncoder** [comment]
Advising: current comment would close 1707. At least 1 Auto test failed independently of this PR. Errors should be fixed, #1702 also failed build and release due to username and password problems.

**Comment by hackerncoder** [comment]
Further advising: #1714 and #1715 failed with the same reasons.

**Comment by Perflyst** [comment]
@hackerncoder I just fixed the container release, though this and other PRs would need a rebase to get the new CI yml.

https://github.com/iv-org/invidious/pull/1712/checks?check_run_id=1783796048 probably fails because of the actions cache, dunno yet. GitHub does not support clearing cache https://github.com/actions/cache/issues/2

**Comment by tenpura-shrimp** [comment]
The new videojs works alot better after this version bump.

I'm seeing much more reliable playback on dash and hls.

**Comment by Rjevski** [comment]
This appears to work successfully in both Safari and Firefox on macOS at least. I'll keep using it on my instance and will report back if I encounter any issues.

**Comment by Perflyst** [comment]
LGTM. @saltycrys any objections? You mentioned some issues with videojs to me in the past, maybe they are solved with the updated version now?

**Comment by saltycrys** [comment]
> @saltycrys any objections?

No.

> You mentioned some issues with videojs to me in the past, maybe they are solved with the updated version now?

Hopefully. Some of the issues are caused by plugins though.

**Pull request merged**
