### PR TITLE
Add param 8AEB for getting youtube stories

### PR DESCRIPTION
**Pull request by unixfox**
Example youtube story: https://redirect.invidious.io/watch?v=VboqVu0_tKA

Parameter given by coletdjnz on matrix. Already used in yt-dlp

### CODE REVIEW

**Comment by SamantazFox** [comment]
Seems like there is something causing issues:

Title: `Missing JSON element "videoPrimaryInfoRenderer" (BrokenTubeException)`
Date: `2022-08-12T19:04:20Z`
Route: `/watch?v=VboqVu0_tKA`
Version: `2022.08.07-9cc04187 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element "videoPrimaryInfoRenderer" (BrokenTubeException)
  from invidious.git/src/invidious/videos.cr:976:3 in 'parse_video_info'
  from invidious.git/src/invidious/videos.cr:923:3 in 'extract_video_info:video_id'
  from invidious.git/src/invidious/videos.cr:1123:3 in 'fetch_video'
  from invidious.git/src/invidious/videos.cr:1111:13 in 'get_video'
  from invidious.git/src/invidious/videos.cr:1094:1 in 'get_video:region'
  from invidious.git/src/invidious/routes/watch.cr:63:15 in 'handle'
  from invidious.git/src/invidious.cr:332:1 in '->'
  from invidious.git/lib/kemal/src/kemal/route.cr:12:26 in '->'
  from invidious.git/src/invidious/helpers/handlers.cr:30:37 in 'process_request'
  from invidious.git/lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/ext/kemal_static_file_handler.cr:188:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment]
@unixfox Video is now unavailable, it seems :/

**Comment by B0pol** [comment]
> @unixfox Video is now unavailable, it seems :/

It’s not available on YouTube but still available with yt-dlp and CloudTube https://tube.cadence.moe/watch?v=VboqVu0_tKA

**Comment by SamantazFox** [comment]
> It’s not available on YouTube but still available with yt-dlp and CloudTube https://tube.cadence.moe/watch?v=VboqVu0_tKA

`[youtube] VboqVu0_tKA: Video unavailable. This video has been removed by the uploader`

**Comment by 4cq2** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30725

**Pull request merged**
