### PR TITLE
Fill empty preference values

### PR DESCRIPTION
**Pull request by saltycrys**
See https://github.com/iv-org/invidious/issues/1253

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
Tested and working, however I'm a bit scared that this will break stuff, so we'll wait for a proper code review.

**Comment by saltycrys** [comment]
This is a visual change only.

From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option:

> **value**
> The content of this attribute represents the value to be submitted with the form, should this option be selected. If this attribute is omitted, the value is taken from the text content of the option element.

The value attribute is never omitted so the text content is never submitted.

**Comment by TheFrenchGhosty** [comment]
So if I understand correctly:

- this won't affect the existing cookies that store the settings
- this won't affect the URL parameters
- this won't affect the instance configuration (example: https://github.com/TheFrenchGhosty/PussTheCat.org-Configs/blob/master/Services/Invidious/config.yml#L32 where the second source is set to nothing)


An empty value will still act correctly in those or won't need to be updated with "none" instead of the empty value? Correct?

**Comment by saltycrys** [comment]
Yes, correct. I went through and added visual, front-end only displays of empty preference values. The preference values themselves are still empty.

**Comment by TheFrenchGhosty** [comment]
@saltycrys Okay, thanks. merging.

**Comment by saltycrys** [comment]
"Fill empty preference values" was a bad title for this. What I was referring to was the value of the dropdowns on the preferences page, but with value being such a generic term and then talking about the value attribute of the HTLM option element it got too confusing.

A better title would have been "Improve display of empty dropdown values on preferences page".

**Pull request merged**
