### PR TITLE
Bump kemal dependency to v1.1.1

### PR DESCRIPTION
**Pull request by SamantazFox**
Solves broken playback on crystal 1.3.*
See: https://github.com/kemalcr/kemal/pull/628
Closes: https://github.com/iv-org/invidious/issues/2783

### CODE REVIEW

**Comment by SamantazFox** [comment]
Ah!

https://github.com/kemalcr/kemal/commit/a251ede5bdbf9ce41c238530839cce5a7206930c
https://github.com/kemalcr/kemal/commit/db0a6b8dc6506681fa292b5e4042872a9ecee8c0

**Review by matthewmcgarvey — APPROVED** [review]

**Comment by SamantazFox** [comment]
deployed on https://test.invidious.io

**Comment by unixfox** [comment]
> deployed on [test.invidious.io](https://test.invidious.io)

Strangely it doesn't work with dash on firefox and safari.

**Comment by SamantazFox** [comment]
@unixfox mind trying again? I've probably broken something this morning when working on the test instance.

**Comment by unixfox** [comment]
Ok but the instance is a bit broken, the page is generated twice lol.
image

**Comment by matthewmcgarvey** [comment]
O! I was watching a friend streaming yesterday and trying to learn kemal and the exact same thing happened to him. I think this is a bug in kemal or whatever the html renderer is

**Comment by SamantazFox** [comment]
> O! I was watching a friend streaming yesterday and trying to learn kemal and the exact same thing happened to him. I guess this might be a bug in kemal or whatever the html renderer is

Kemal dropped kilt for ECR between v.1.1.0 (last version we used) and 1.1.1 (version that contains my PR that fixes playback on Crystal 1.3.*). So I think that kilt and ECR don't react the same to the template files.

**Comment by matthewmcgarvey** [comment]
https://github.com/kemalcr/kemal/pull/631

**Comment by matthewmcgarvey** [comment]
@SamantazFox fix has been merged and we'll need to update to v1.1.2

**Pull request closed without merging**
