### PR TITLE
Widen Youtube player seek bar a little

### PR DESCRIPTION
**Pull request by DUOLabs333**
This makes it easier to click on points.

Result:
image

### CODE REVIEW

**Comment by SamantazFox** [comment]
Nice! Can you please post a screenshot of the result, as it is an UI change?

**Comment by DUOLabs333** [comment]
Added.

**Comment by SamantazFox** [comment]
It seems that the progress bar is flaoting:
image

**Comment by DUOLabs333** [comment]
Huh, didn't notice that. Not sure how to fix it though.

**Comment by SamantazFox** [comment]
It's probably the `margin-bottom` that has to be adjusted :)

**Comment by DUOLabs333** [comment]
Should be fixed now.

**Comment by SamantazFox** [comment]
Heck, now I recall why I haven't tried to fix that stuff. The rest, around the progress bar, also need to be tweaked so everything looks as expected.

See how everything is weird on hover?
image

**Comment by DUOLabs333** [comment]
Weird, it looks fine for me, that's why I didn't change anything else.

**Comment by SamantazFox** [comment]
@DUOLabs333 what browser are you using?

**Comment by DUOLabs333** [comment]
Firefox

**Comment by DUOLabs333** [comment]
Here's what it looks like for me:
image

**Comment by SamantazFox** [comment]
> Here's what it looks like for me

Damn... I've made the screenshot on Firefox, too.

I guess I'll never understand browsers...

**Pull request merged**
