### PR TITLE
Display username of currently logged in user

### PR DESCRIPTION
**Pull request by makos**
Closes: #689

After the disaster that was #1008, I made a new clean branch with current master branch as the base. Patched in all my changes from the old PR. All should be good now.

### CODE REVIEW

**Comment by makos** [comment]
My commit didn't touch anything Docker or DB related, yet Travis fails to bring up Postgres inside the Docker container. I tried out many things but I'm stuck now. The `.travis.yml` file doesn't differ from the (contemporary) file from your master branch. Same for `Dockerfile`, `docker-compose.yml` or any of the DB migrations etc. So why is this happening?

**Comment by leonklingele** [comment]
@makos you might want to rebase to latest master. The issue with PostgreSQL was fixed in https://github.com/omarroth/invidious/commit/c80c5631f0483c32c3b86bad3584c349a61b4b92.

**Comment by makos** [comment]
I am sorry for the mess; I don't know how to not include the whole master history while rebasing. But the PR builds, works, and is able to be merged. If this is not OK I can redo this whole thing on a new branch without the master history.

**Comment by omarroth** [comment]
No worries. I've rebased your branch against master. I'll give it a proper review when I have a bit more time.

**Comment by GauthierPLM** [comment]
@TheFrenchGhosty @Perflyst could you review this/rebase the changes? I think it would be a useful feature.

**Comment by unixfox** [comment]
@syeopite "Welcome" is not really necessary.

**Pull request merged**
