### PR TITLE
Improve atom feeds

### LINKED ISSUE #1064: Suggestion: set icon element to channel logo on atom feeds
When you have a large number of invidious feeds in your feed reader (I personally have over 30) it quickly becomes unmanageable when they all have the same icon. Setting the [icon tag](https://tools.ietf.org/html/rfc4287#section-4.2.5) to the channel logo whenever possible would help with this.

### LINKED ISSUE #2248: [Feature request] Better RSS Feeds
**Is your enhancement request related to a problem? Please describe.**

RSS Feeds are not the best, as you need to open the Link before you can watch the Videos

**Describe the solution you'd like**

Add an iframe with the invidious embed

### LINKED ISSUE #2249: [Enhancement] Better Subs RSS
**Is your enhancement request related to a problem? Please describe.**

The Feed does not say when it got published in tt rss, but when they have been added to the feed, I guess

**Describe the solution you'd like**

Remove the updated attribute from the Articles in the feed

### PR DESCRIPTION
**Pull request by SamantazFox**
Make the following changes to Atom feeds:
- Remove non-standard `<yt:videoId>` and `<yt:channelId>` elements
- Make entry IDs RFC compliant (must be an URI) => This should also prevent some web-based RSS readers from embedding the youtube player
- Base all URLs (icons, links, etc) on `HOST_URL`
- Fix the different problems reported by W3C validator

Notes:
- RSS feeds are TODO
- Player can't be embedded without breaking RFC compliance (See why in issues listed below)

Fixes #1064
Fixes #2248
Fixes #2249

### CODE REVIEW

**Comment by Loki-L1130** [comment]
Anything else to be done @SamantazFox ?

**Comment by SamantazFox** [comment]
@Loki-L1130 yes! See the `.to_xml` methods here and there? Those needs to be cleaned up and merged into a single function.

**Comment by Loki-L1130** [comment]
>See the `.to_xml` methods here and there? Those needs to be cleaned up and merged into a single function.

Well, I presume, It would take about an Hour to fix though. I just made a comment because the Github bot marked it as `stale` and to close in 30 Days if without any activity. So, I did pinged you.

**Comment by SamantazFox** [comment]
> > See the `.to_xml` methods here and there? Those needs to be cleaned up and merged into a single function.
> 
> Well, I presume, It would take about an Hour to fix though. I just made a comment because the Github bot marked it as `stale` and to close in 30 Days if without any activity. So, I did pinged you.

yeah, the bot marks PRs as "stale" if there wasn't activity for 30 days. Don't worry, though, I see the notifications and remove the label in the ay after, or so. I'm just very busy IRL atm, so I haven't got the time to work on that feature.

**Comment by SamantazFox** [comment]
Deployed on test.invidious.io

**Comment by absidue** [comment]
Hiii
As requested I'm leaving a comment here about this pull request requiring changes on the FreeTube side, as we use the `<yt:videoId>` elements, which are present in the YouTube feeds too. We currently use the same code to parse both the YouTube RSS and Invidious Atom feeds, however with this change we'll likely need to split up the parsing, to handle the two different feeds.

Please let us know when this pull request is ready to merge, so we can make the necessary changes on our side, thanks in advance :).

https://github.com/FreeTubeApp/FreeTube/blob/c2235ade8a66b7f0554d63ac8da59c7d26531ded/src/renderer/views/Subscriptions/Subscriptions.js#L433-L463

**Pull request closed without merging**
