### PR TITLE
YtAPI: Bump client versions

### PR DESCRIPTION
**Pull request by SamantazFox**
Might help reducing the amount of playback errors

### CODE REVIEW

**Review by unixfox — APPROVED** [review]

**Comment by SamantazFox** [comment]
Do you want me to bump the User-Agent too?

**Comment by unixfox** [comment]
> Do you want me to bump the User-Agent too?

good idea

**Comment by SamantazFox** [comment]
done

**Comment by unixfox** [comment]
related: https://github.com/iv-org/invidious/pull/4851

**Review by unixfox — APPROVED** [review]

**Comment by unixfox** [comment]
@SamantazFox can we merge into master branch?

**Review by syeopite — APPROVED** [review]
I'm also for merging this as soon as possible

**Pull request merged**
