### PR TITLE
CSS: display pointer cursor when hovering the "show more/less" toggle

### PR DESCRIPTION
**Pull request by brackets0**
Just fix on hover #descexpansionbutton to pointer

### CODE REVIEW

**Comment by unixfox** [comment]
can you give a little more explanations about this PR?

**Comment by brackets0** [comment]
i just thougth to fix this minimal css "issue", to get a more consistency (i mean why not css pointer on this btn?).
is also fine if that dosen't arrive the app. i found more of this small css missing feautures.

**Comment by SamantazFox** [comment]
I'm not entirely sure to get it: `#descexpansionbutton` is a hidden checkbox, so it can't be hovered.

Do you want to have a pointer over the `show more/less` label (`#descexpansionbutton ~ label`)?
image

(Btw, that button could see some padding too!)

**Comment by brackets0** [comment]
yes, exactly!

**Comment by SamantazFox** [comment]
> yes, exactly! Haven't seen that it is a hidden checkbox, sry.

No problem ^^

**Comment by brackets0** [comment]
i changed the commit code so that the label reflect on hover.

**Review by SamantazFox — APPROVED** [review]

**Comment by SamantazFox** [comment]
Thank you for your contribution :)

**Pull request merged**
