### PR TITLE
Dockerfile: Pass '-Ddisable_quic' to 'crystal build'

### PR DESCRIPTION
**Pull request by SamantazFox**
This is a follow-up to #3367 and a desperate attempt to fix the memory leak issues invidious is having.

### CODE REVIEW

**Comment by unixfox** [comment]
Would prefer to have a special docker image tag for that instead.

**Comment by SamantazFox** [comment]
> Would prefer to have a special docker image tag for that instead.

I think that many of the memory leak issues we're having at the moment are related to QUIC.
Until the dependency is updated and stabilized, I'd prefer that we don't ship it in the release containers.

In addition to that, the version of BoringSSL we're shipping is very outdated (and can't be updated without updating lsquic too). As it collides with the system's own OpenSSL lib, that's not good for security (though it has almost no impact in the context of a container behind a reverse proxy).

**Comment by unixfox** [comment]
I'll update your code in order to have the default docker image without quic and an additionnal docker image with a special tag with quic included.

**Comment by SamantazFox** [comment]
Forgot to mention that this is related to #1438

**Pull request merged**
