### PR TITLE
fixes for crystal 1.1.0

### PR DESCRIPTION
**Pull request by tleydxdy**
fix for https://github.com/iv-org/invidious/issues/2256

### CODE REVIEW

**Comment by unixfox** [comment]
Is this fix still working for crystal 1.0.0?

**Comment by tleydxdy** [comment]
I don't have a 1.0.0 to test now, but seeing as the test passed, it should. There's not much that was changed, mostly to guide the compiler back to the old track. ofc testing on 1.0.0 is probably a good idea.

**Comment by Perflyst** [comment]
Works fine with crystal 1.0.0

**Review by Perflyst — APPROVED** [review]

**Comment by tleydxdy** [comment]
the json parsing part should be fixed by 1.1.1 now https://github.com/crystal-lang/crystal/pull/10972
However, it may not be a good idea to use Int64 anyway.

**Comment by SamantazFox** [comment]
@tleydxdy Why using `Int64` is a bad idea? What's wrong about it?

**Comment by syeopite** [comment]
Superseded by #2295

**Pull request closed without merging**
