### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by saltycrys**

### CODE REVIEW

**Comment by FireMasterK** [comment]
I believe this is causing issues, see: https://github.com/iv-org/invidious/issues/1791

**Comment by unixfox** [comment]
Can we have a revert on this PR?

**Comment by Perflyst** [comment]
I have reverted it. The patchset worked fine without docker in my tests

**Comment by saltycrys** [comment]
I forgot to update the Dockerfile, sorry about that.

See https://github.com/iv-org/invidious/issues/1791#issuecomment-785847087

**Pull request merged**
