### PR TITLE
Remove lsquic entirely

### PR DESCRIPTION
**Pull request by syeopite**
Seems to work fine though I have no way of making sure the storyboard functionalities are kept since I can't test that on my local instance. It should be tested just in case. 

Close https://github.com/iv-org/invidious/issues/3752

### CODE REVIEW

**Comment by syeopite** [comment]
Amoeba is broken on Crystal 1.9. See https://github.com/crystal-ameba/ameba/issues/372. Once v1.5 of Ameba comes out it should be fixed.

**Review by unixfox — APPROVED** [review]

**Review by SamantazFox — APPROVED** [review]
Code looks good!

**Comment by unixfox** [comment]
I would like to merge this because I have been using invidious without quic compiled for months and this works great.

**Comment by syeopite** [comment]
Safe to merge then?

**Comment by unixfox** [comment]
Merging as it's has been stable for a long time now.

**Pull request merged**
