### PR TITLE
Update Chart.yaml

### LINKED ISSUE #3529: [Bug] Issue with kubernetes helm chart for Invidious - cannot install
Issue with kubernetes helm chart for Invidious. Short research suggests that Bitnami removed their older Postgresql chart and this might be causing it. Change in Invidious helm chart is required to refer to proper Postgresql version / chart as a dependency.

**Steps to Reproduce**

1. Clone invidious git repo:

git clone https://github.com/iv-org/invidious.git invidious-git

Cloning into 'invidious-git'...
remote: Enumerating objects: 24070, done.
remote: Counting objects: 100% (294/294), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 24070 (delta 172), reused 227 (delta 138), pack-reused 23776
Receiving objects: 100% (24070/24070), 22.23 MiB | 7.57 MiB/s, done.
Resolving deltas: 100% (16044/16044), done.

2. update dependencies with helm:

cd invidious-git/kubernetes

helm dependency build
helm dependency update

Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "longhorn" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "nextcloud" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "kfirfer" chart repository
...Successfully got an update from the "truecharts" chart repository
...Successfully got an update from the "nicholaswilde" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Save error occurred:  could not find : no matching version
Error: could not find : no matching version
creating namespace ...
Error from server (AlreadyExists): namespaces "invidious" already exists **# namespace already existed. This is irrelevant**

3. create configmap:

kubectl create configmap invidious-postgresql-init \
  --from-file=../config/sql/channels.sql \
  --from-file=../config/sql/videos.sql \
  --from-file=../config/sql/channel_videos.sql \
  --from-file=../config/sql/users.sql \
  --from-file=../config/sql/session_ids.sql \
  --from-file=../config/sql/nonces.sql \
  --from-file=../config/sql/annotations.sql \
  --from-file=../config/sql/playlists.sql \
  --from-file=../config/sql/playlist_videos.sql -n invidious

error: failed to create configmap: configmaps "invidious-postgresql-init" already exists **# this is irrelevant. I did not remove old configmap**

4. install helm chart:

helm install invidious --create-namespace -f values.yaml -n invidious

Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: postgresql

Additional notes:

helm version
version.BuildInfo{Version:"v3.10.2", GitCommit:"", GitTreeState:"", GoVersion:"go1.19.4"}

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.8+k0s

kubernetes distribution: k0s

### PR DESCRIPTION
**Pull request by marcxm**
Set postgresql Chart version to 12.1.6. Bitnami deleted 11.1.3.

Closes #3529

### CODE REVIEW

**Comment by unixfox** [comment]
Is this the postgres version? Is so we can bump it to postgresql 14.

**Comment by unixfox** [comment]
> @unifox We can't, due to #2938.

Or Postgres 13, at least it's newer than 12

**Comment by SamantazFox** [comment]
Can you please explain to the noob k8s that I am what those two changes do?
I'm not sure what ends up being selected between `version: ~11.1.3` and `tag: 13`.

**Comment by unixfox** [comment]
This is about the kubernetes helm chart for invidious: https://helm.sh/docs/topics/charts/

The version `version: ~11.1.3` is for the version of the helm chart used: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/Chart.yaml#L29

And `tag` is for using the docker tag `13` for this docker image: https://hub.docker.com/r/bitnami/postgresql

**Pull request merged**
