### PR TITLE
fix comment replies

### LINKED ISSUE #1811: [Bug] Comments replies are broken
**Describe the bug**

Comments replies don't work and just load the comments.

**Steps to Reproduce**

Go to any video, and try to load the replies of a comment.

**Logs**

N/A

**Screenshots**

Gif:

gif

**Additional context**

 - Browser (if applicable): N/A
 - OS (if applicable): N/A

Related PR: https://github.com/iv-org/invidious/pull/1795

### PR DESCRIPTION
**Pull request by tenpura-shrimp**
Fixes #1811 
I want to be awarded the bounty associated to the issue this PR is fixing.

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
Tested.

This kinda works, replies works by clicking "View X replies", however for comments with a lots of replies, clicking "Load more" to load more replies won't do anything, and the browser console will report a 500 error.

**Comment by tenpura-shrimp** [comment]
Hm maybe the pagination of the replies needs to have action replies as well.

Can you check adding &action=action_get_comment_replies to the end of the 500ed url and verifying if that succeeds?

**Comment by TheFrenchGhosty** [comment]
@tenpura-shrimp Adding &action=action_get_comment_replies at the end of the URL seem to indeed works, the API seems to be correctly returning content, so it's maybe the solution.

s

**Review by saltycrys — APPROVED** [review]

**Comment by saltycrys** [comment]
Please note that when I review I only look at the code and do no testing.

**Comment by tenpura-shrimp** [comment]
@TheFrenchGhosty Updated to fix the issue.  Please re-test as needed.

**Comment by TheFrenchGhosty** [comment]
@tenpura-shrimp Tested. This is working perfectly now!

**Comment by TheFrenchGhosty** [comment]
@saltycrys Can you re-review this PR so that it can be merged please.

**Review by saltycrys — APPROVED** [review]

**Comment by TheFrenchGhosty** [comment]
Merged.

Thank you @tenpura-shrimp 

Thanks for the review @saltycrys 

@tenpura-shrimp to receive your reward either send you BTC address in a comment (preferred), or contact us, with a proof that this is indeed you.

**Comment by tenpura-shrimp** [comment]
Proof for the bounty: (udk~*yWrJto(Qk7Y?h-3J?E+g(%6@(/^WS<`/0Jz<T+5T(RL\6+Cf{Fk7$$p.Wze!m.\)M'>k=t](370(cS}v;vq8vZyo;o=r+GW13pWnQ)t,T\`vE=9OH*Rna>%u)S

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been rewarded to @tenpura-shrimp 

Transaction (953f8767f3332309009afe24ce19192bee0f8bf0dbf5ffdc3a082896c1137264):

Amount sent: 0.00036395 BTC (~16.73€ or ~20$)

Mining fees (30 sat/byte): 0.0000426 BTC (~1.96€)

**Pull request merged**
