### PR TITLE
Add support for the new channel layout (part 2)

### PR DESCRIPTION
**Pull request by SamantazFox**
Fixes (again) partially #3371

### CODE REVIEW

**Comment by SamantazFox** [comment]
Hmm, there are some weird things still going on...

```
Missing JSON element "reelPlayerHeaderSupportedRenderers" (BrokenTubeException)
  from invidious.git/src/invidious/yt_backend/extractors.cr:426:16 in 'parse'
  from invidious.git/src/invidious/yt_backend/extractors.cr:404:16 in 'process'
  from invidious.git/src/invidious/yt_backend/extractors.cr:386:17 in 'parse'
  from invidious.git/src/invidious/yt_backend/extractors.cr:380:16 in 'process'
  from invidious.git/src/invidious/yt_backend/extractors.cr:741:17 in 'parse_item'
  from invidious.git/src/invidious/yt_backend/extractors.cr:787:14 in 'extract_items'
  from invidious.git/src/invidious/channels/videos.cr:139:12 in 'get_shorts'
  from invidious.git/src/invidious/routes/api/v1/channels.cr:177:35 in 'shorts'
  from invidious.git/src/invidious/routing.cr:210:5 in '->'
  from invidious.git/lib/kemal/src/kemal/route.cr:12:26 in '->'
  from invidious.git/src/invidious/helpers/handlers.cr:30:37 in 'process_request'
  from invidious.git/lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/handlers.cr:158:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from invidious.git/lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```

**Comment by SamantazFox** [comment]
> Have you guys determined if arbitrary paging is possible with the new ctoken format? I did some experimentation and managed to get it to retrieve different pages by playing with the values, however I haven't yet checked if there's a server side check that prevents it from skipping pages

I've tried, and so far none of my attempts were successful. If you have a solution, I'll happily take it, but otherwise, I won't spend much more time fiddling around.

**Comment by unixfox** [comment]
In testing on https://yewtu.be

**Review by unixfox — APPROVED** [review]
Great thank you. we didn't receive any bug report

**Pull request merged**
