### PR TITLE
Config improvements

### PR DESCRIPTION
**Pull request by saltycrys**
**Add config environment variables**

The config file can now be specified with `INVIDIOUS_CONFIG_FILE`.
A YAML formatted string can still be passed with `INVIDIOUS_CONFIG`, replacing
the config file.

Additionally all options can now be specified as environment variables.
The syntax for variable names is `INVIDIOUS_` followed by the option name in
upper case. The values are parsed as YAML.

These new env vars only update the provided main configuration, but it is
possible to point the config file at the example config and then use env vars
for all config options:
```
INVIDIOUS_CONFIG_FILE=./config/config.example.yml \
INVIDIOUS_CHANNEL_THREADS=10 \
./invidious
```

**Make config a constant**

Instead of passing around `config` there is now the global `CONFIG`.

**Only start refresh jobs when necessary**

If `channel_threads` or `feed_threads` is set to zero the corresponding job is
now not started.

<hr>

Closes https://github.com/iv-org/invidious/issues/1677

### CODE REVIEW

**Comment by Perflyst** [comment]
OT @FireMasterK looks like building an image for PR does not work because the secret is only available from with-in the repo :/

**Comment by FireMasterK** [comment]
Look like they're no way to allow forks to access them too. (Safely)

**Comment by Perflyst** [comment]
I get two errors:
```
[error] UpdateDecryptFunctionJob : Nil assertion failed
[error] BypassCaptchaJob: Missing hash key: "taskId"
```

**Comment by saltycrys** [comment]
Please try with f1a7ee9 to see if the config constant is the problem.

**Comment by Perflyst** [comment]
Just reverted and tested with https://github.com/iv-org/invidious/commit/f1a7ee997b5f6bc52388473dcd1b8043c5ceacff happens there too. Then I went back to master and it happens on master too so the errors are not related to this patch at all

**Comment by saltycrys** [comment]
Seems like you're getting empty responses when doing web requests. Can you try with a machine that has a different internet connection?

**Comment by Perflyst** [comment]
Works fine locally

**Review by Perflyst — APPROVED** [review]

**Comment by Rjevski** [comment]
> If channel_threads or feed_threads is set to zero the corresponding job is
now not started.

Does this mean workers can now be offloaded to a separate process? Ie. run the main web process with channel_threads and feed_threads to 0, and run a process in the background with those values set to non-zero?

**Comment by saltycrys** [comment]
> Does this mean workers can now be offloaded to a separate process? Ie. run the main web process with channel_threads and feed_threads to 0, and run a process in the background with those values set to non-zero?

Yes, but technically that was already possible.
What happened was that the jobs started and immediately stalled. The `RefreshChannelsJob` has some logging at startup that would always get logged, now it only happens with a non-zero config value.

**Pull request merged**
