### PR TITLE
actual fix large playlists

### LINKED ISSUE #1883: [Bug] Playlists with 100+ videos don't display any videos on any instance.
Once again, can't make the default template display correctly so...
OS: ChromeOS
Browser: Chrome Version 87.0.4280.152 (Official Build) (64-bit)

Steps to reproduce issue:
1. Go to any invidious instance
2. Go to any playlist with over 100 videos
3. See no videos whatsoever

Screenshots: 
Screenshot 2021-03-11 at 2 09 52 PM
Screenshot 2021-03-11 at 2 09 40 PM

### PR DESCRIPTION
**Pull request by tenpura-shrimp**
Fixes #1883 
I want to be awarded the bounty associated to the issue this PR is fixing.

### CODE REVIEW

**Comment by SamantazFox** [comment]
The continuation (page 2,3 and so on) doesn't work.

**Comment by TheFrenchGhosty** [comment]
Continuation works on:

https://www.youtube.com/playlist?list=PLYH8WvNV1YEn9PkI2stxJWMs8GRit66Rz

Continuation break after 1 page:


There isn't even a button to go on the next page on this one:

https://www.youtube.com/playlist?list=PLWwAypAcFRgKAIIFqBr9oy-ZYZnixa_Fj

**Comment by SamantazFox** [comment]
Just for traceability/logs, I used the following playlists to test continuation:

https://www.youtube.com/playlist?list=PLNj_ZJF3LtBzxeoqwagc30AgrNvhSUu1L
https://www.youtube.com/playlist?list=PLj3LVjI7cF7k-LmGKRiw6XwbU8SAtQwCF

**Comment by tenpura-shrimp** [comment]
closing in favor of #1911 

Good work @SamantazFox

**Pull request closed without merging**
