### PR TITLE
more polish

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
Unfinished (or finished if it's the only thing that remain to change) and might break stuff if this is used by something else.

### CODE REVIEW

**Comment by matthewmcgarvey** [comment]
can you explain what this is doing, and what would the difference be if this works?

**Comment by TheFrenchGhosty** [comment]
@matthewmcgarvey Take a look at the youtube-dl repo, you will understand. If you want more information, ask in matrix.

**Review by matthewmcgarvey — APPROVED** [review]

**Comment by TheFrenchGhosty** [comment]
@matthewmcgarvey By approving, do you mean that it won't break anything and that it can be merged?

**Comment by matthewmcgarvey** [comment]
@TheFrenchGhosty yea, I checked the links and they work so it will be fine

**Pull request merged**
