### PR TITLE
Fix comment replies count

### PR DESCRIPTION
**Pull request by B0pol**
Fixes https://github.com/iv-org/invidious/issues/1789

### CODE REVIEW

**Comment by Rjevski** [comment]
Appears to work fine on my instance.

**Comment by B0pol** [comment]
image
continuation is also broken

**Comment by 4Kirb** [comment]
I just swapped out the code and rebuilt and this works fantastically, will update if I encounter any issues.

**Review by saltycrys — APPROVED** [review]

**Comment by TheFrenchGhosty** [comment]
Thank you @B0pol 

@4Kirb thank you for testing!

**Pull request merged**
