### PR TITLE
fix larger playlists

### LINKED ISSUE #1883: [Bug] Playlists with 100+ videos don't display any videos on any instance.
Once again, can't make the default template display correctly so...
OS: ChromeOS
Browser: Chrome Version 87.0.4280.152 (Official Build) (64-bit)

Steps to reproduce issue:
1. Go to any invidious instance
2. Go to any playlist with over 100 videos
3. See no videos whatsoever

Screenshots: 
Screenshot 2021-03-11 at 2 09 52 PM
Screenshot 2021-03-11 at 2 09 40 PM

### PR DESCRIPTION
**Pull request by tenpura-shrimp**
Fixes #1883 
I want to be awarded the bounty associated to the issue this PR is fixing.

Known limitation: pagination does not work and it never worked.  But getting something is better than getting nothing.

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
>Known limitation: pagination does not work and it never worked. But getting something is better than getting nothing.

Pagination as in playlists with multiple pages? This is supposed to work, I think.

**Comment by TheFrenchGhosty** [comment]
Tested.

It indeed works on page one, however others pages are indeed empty.

**Comment by SamantazFox** [comment]
> This is supposed to work, I think.

See #1599

**Comment by TheFrenchGhosty** [comment]
@SamantazFox This is a different issue, this is an issue about the playlists list, not the playlist themselves.

**Comment by SamantazFox** [comment]
> @SamantazFox This is a different issue, #1599 is an issue about the playlists list on the channel page, not the playlist themselves.

Ah, my bad....

**Comment by TheFrenchGhosty** [comment]
@SamantazFox No problem, don't worry :)

**Comment by tenpura-shrimp** [comment]
wait I'm being extremely dumb.  I misread the original codez and this isn't what I'm supposed to do.

**Pull request closed without merging**
