### PR TITLE
Add multiple video route aliases. 

### LINKED ISSUE #1736: https://www.youtube.com/watch/videoid support
can this be added to the support?
like this?
https://invidious.kavin.rocks/watch/ZvWn5xBflUs

### PR DESCRIPTION
**Pull request by syeopite**
Adds support for:

- /watch/
- /shorts/
- /e/
- /v/
- /w/

as possible video routes. 

Closes #1736

### CODE REVIEW

**Review by saltycrys — CHANGES_REQUESTED** [review]
All of these redirect to `/watch?q=` so it would be better to add a `Invidious::Routes::Watch :redirect` route for
- `/w/:id`
- `/v/:id`
- `/e/:id`
- `/shorts/:id`
- `/watch/:id`
- 
and leave the main watch route and 404 handler untouched. Basically the inverse of the embed routes.

**Review by saltycrys — APPROVED** [review]

**Comment by Perflyst** [comment]
@TheFrenchGhosty do we need to change anything else on weblate before / after this gets merged?

**Review by Perflyst — APPROVED** [review]
Works great, thanks for your contribution!

**Comment by B0pol** [comment]
what about URL parameters? They are just removed with this PR if using one of these short URLs

**Comment by syeopite** [comment]
> what about URL parameters? They are just removed with this PR if using one of these short URLs

Oops, I forgot about url parameters. #2011 should fix it

**Pull request merged**
