### PR TITLE
Fix CI badge

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Also please see my bug report to Travis: https://travis-ci.community/t/unable-to-locate-package-libevent-dev/9608

**Comment by Perflyst** [comment]
Can you add an apt update as mentioned in https://travis-ci.community/t/unable-to-locate-package-libevent-dev/9608/2 ?

**Comment by szepeviktor** [comment]
No, that is not possible as that apt is way early.

See my dirty work-around!

**Comment by szepeviktor** [comment]
Guys at Travis are working on this.
https://github.com/travis-ci/travis-build/pull/1939

**Pull request merged**
