### PR TITLE
YoutubeAPI: bump client versions

### PR DESCRIPTION
**Pull request by SamantazFox**

### CODE REVIEW

**Review by unixfox — APPROVED** [review]

**Review by syeopite — APPROVED** [review]
Lint just needs to be fixed

**Comment by SamantazFox** [comment]
> Lint just needs to be fixed

I'm not sure what to fix?

image

**Comment by SamantazFox** [comment]
Nevermind, I found the lint issue. Idk why I forgot to run `make format` in the first place...

**Comment by unixfox** [comment]
Merging as many people seems to have issues with instance being blocked. Updating the client versions will probably help.

**Comment by unixfox** [comment]
> Updated versions didn't help for me, YouTubeAPI returned 500. Here is the trace log, if it helps:
> ```
> 2024-03-09 00:09:28 UTC [trace] fetch_channel: UCYTi7HrzJFhr5EHRefNuvaQ : Downloading channel videos page
> 2024-03-09 00:09:28 UTC [debug] YoutubeAPI: Using endpoint: "/youtubei/v1/browse"
> 2024-03-09 00:09:28 UTC [trace] YoutubeAPI: ClientConfig: YoutubeAPI::ClientConfig(@client_type=YoutubeAPI::ClientType::Web, @region="US", @proxy_region=nil)
> 2024-03-09 00:09:28 UTC [trace] YoutubeAPI: POST data: {"context" => {"client" => {"hl" => "en", "gl" => "US", "clientName" => "WEB", "clientVersion" => "2.20240304.00.00", "clientScreen" => "WATCH_FULL_SCREEN", "osName" => "Windows", "osVersion" => "10.0", "platform" => "DESKTOP"}}, "continuation" => "4qmFsgKvARIYVUNZVGk3SHJ6SkZocjVFSFJlZk51dmFRGmQ4Z1pJR2taNlJBb1lDaFpGWjBsSlFVTm5lVTFCUlRSSWEyZENWVUZCSlRORUVpWUtKREF3TURBd01EQXdMVEF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF3TURBd01EQXdNQmdCmgIsYnJvd3NlLWZlZWRVQ1lUaTdIcnpKRmhyNUVIUmVmTnV2YVF2aWRlb3MxMDI%3D"}
> 2024-03-09 00:09:28 UTC [error] YoutubeAPI: Got error 500 when requesting /youtubei/v1/browse
> 2024-03-09 00:09:28 UTC [error] YoutubeAPI: Internal error encountered.
> 2024-03-09 00:09:28 UTC [info] YoutubeAPI: POST data was: {"context" => {"client" => {"hl" => "en", "gl" => "US", "clientName" => "WEB", "clientVersion" => "2.20240304.00.00", "clientScreen" => "WATCH_FULL_SCREEN", "osName" => "Windows", "osVersion" => "10.0", "platform" => "DESKTOP"}}, "continuation" => "4qmFsgKvARIYVUNZVGk3SHJ6SkZocjVFSFJlZk51dmFRGmQ4Z1pJR2taNlJBb1lDaFpGWjBsSlFVTm5lVTFCUlRSSWEyZENWVUZCSlRORUVpWUtKREF3TURBd01EQXdMVEF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF3TURBd01EQXdNQmdCmgIsYnJvd3NlLWZlZWRVQ1lUaTdIcnpKRmhyNUVIUmVmTnV2YVF2aWRlb3MxMDI%3D"}
> 2024-03-09 00:09:28 UTC [error] RefreshChannelsJob: UCYTi7HrzJFhr5EHRefNuvaQ : Could not extract JSON. Youtube API returned error 500 with message:<br>"Internal error encountered."
> ```

Please create a separate issue.

**Pull request merged**
