### PR TITLE
Move omar.yt/lsquic/liblsquic-v2.18.1.a to GitHub.

### LINKED ISSUE #1414: The Dockerfile curl a file hosted on omar.yt
The Dockerfile curl a file hosted on omar.yt: https://github.com/iv-org/invidious/blob/master/docker/Dockerfile#L11

Since omarroth left invidious this file needs to be moved somewhere else, preferably Github.

### PR DESCRIPTION
**Pull request by ChaseHall**
Closes #1414.
Think I got it right.

Edit: this will obviously error until you merge it. It should work then though.

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
I looked a bit more, and it looks like this file is actually built from https://github.com/iv-org/lsquic.cr/releases/tag/v2.18.1 since we updated lsquic.cr, I'm guessing we need to rebuild it, and, I'm guessing it's a good idea to actually put the file in the release page of lsquic.cr.

I might be wrong, obviously but I think this is the correct thing to do.

I wonder why the release was on omar.yt and not github though @omarroth

**Comment by FireMasterK** [comment]
Why not build lsquic.cr in the Dockerfile instead of using a precompiled binary? It should also make room for other architectures too technically

**Comment by Perflyst** [comment]
That would need quite a lot resources.

I expect these two files are the same (already checked shasums, those are different though):
https://omar.yt/lsquic/liblsquic-v2.18.1.a
https://raw.githubusercontent.com/iv-org/lsquic.cr/master/src/lsquic/ext/liblsquic.a

Why I am thinking this? See https://github.com/iv-org/invidious/issues/1257#issuecomment-660658614

**Comment by TheFrenchGhosty** [comment]
Closing, see: https://github.com/iv-org/invidious/issues/1414#issuecomment-710494532

**Pull request closed without merging**
