### PR TITLE
new method for bypassing age restriction

### PR DESCRIPTION
**Pull request by unixfox**
Use the new method from https://github.com/yt-dlp/yt-dlp/pull/3233
Related  to https://github.com/iv-org/invidious/issues/2189

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
*Copied from https://github.com/iv-org/invidious/issues/2189#issuecomment-1082318444*

Here's 4 SFW videos that are age restricted, for testing purpose:

https://youtube.com/watch?v=FISUqoODw9Q
https://youtube.com/watch?v=KVjHwrKJg8k
https://youtube.com/watch?v=h16HA4XjyD8
https://youtube.com/watch?v=FISUqoODw9Q

**Comment by unixfox** [comment]
Due to the fact that we aren't decrypting the n "thing" for getting a faster download speed, loading an age restricted video is very slow.

**Comment by TheFrenchGhosty** [comment]
4 issues:

- Release date of those videos is displayed as the current date
- No description
- `Genre: ` is empty
- `Whitelisted regions:  ` is displayed

**Comment by unixfox** [comment]
> 4 issues:
> 
>     * Release date of those videos is displayed as the current date
> 
>     * No description
> 
>     * `Genre: ` is empty
> 
>     * `Whitelisted regions:  ` is displayed

One way to fix this issue is to merge the data from the WEB client and the TVHTML5 client

**Comment by TheFrenchGhosty** [comment]
If it's a lot of work, it might be a good idea to merge this PR as-is, so that videos can at least play.

**Review by SamantazFox — APPROVED** [review]

**Pull request merged**
