### PR TITLE
Redesign videojs player controls for better mobile usage

### LINKED ISSUE #912: Control bar broken on mobile
The playback bar is too narrow to accurately seek videos in portrait mode on mobile, making it difficult to navigate very long videos.

In Firefox Preview:

Screenshot_20191115-093159

Contrast with the official YouTube app:

Screenshot_20191115-093316

It seems like the other video UI would have to be moved to accommodate this.

### PR DESCRIPTION
**Pull request by Ruin0x11**
Closes #912.

This PR changes the player controls so the seek bar always fits the width of the screen. This makes seeking far easier in portrait mode on mobile devices. The controls are also larger for easier touch input.

The theme is based on the [city](https://github.com/videojs/themes/tree/master/city) theme provided by Video.js.

Previous:

New:

### CODE REVIEW

**Comment by lucky13820** [comment]
This is great, are we ever going to merge this PR?

**Comment by TheFrenchGhosty** [comment]
Merge conflict fixed.

**Comment by TheFrenchGhosty** [comment]
PR tested and it's not working properly:

First, it "kinda" work on PC but makes the quality control go over the UI, this isn't good.

s

Second, quality still can't be changed on mobile, because only the first 2 are visible:

mobile

**Comment by TheFrenchGhosty** [comment]
Superseded by #2008

**Pull request closed without merging**
