### PR TITLE
Raise error if video not playable, also handle missing related videos

### LINKED ISSUE #2877: [Bug] Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)
**Describe the bug**
The video with ID 7IpVsQVyok8 cannot be loaded in Invidious.

**Steps to Reproduce**
1. Go to /watch?v=7IpVsQVyok8
2. Note that it has not worked

**Logs**
Title: `Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)`
Date: `2022-02-09T02:29:47Z`
Route: `/watch?v=7IpVsQVyok8`
Version: `2022.02.09-4272ee7 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element &quot;twoColumnWatchNextResults&quot; (BrokenTubeException)
  from /usr/lib/crystal/core/json/any.cr:102:10 in &#39;extract_video_info:video_id&#39;
  from /usr/lib/crystal/core/hash.cr:1139:13 in &#39;get_video:region&#39;
  from src/invidious/routes/watch.cr:63:15 in &#39;handle&#39;
  from lib/kemal/src/kemal/route.cr:13:9 in &#39;-&gt;&#39;
  from /usr/lib/crystal/core/primitives.cr:266:3 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from src/invidious/helpers/static_file_handler.cr:167:15 in &#39;call&#39;
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/init_handler.cr:12:7 in &#39;process&#39;
  from /usr/lib/crystal/core/http/server.cr:500:5 in &#39;-&gt;&#39;
  from /usr/lib/crystal/core/primitives.cr:266:3 in &#39;run&#39;
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in &#39;??&#39;
```
</p>
</details>

### PR DESCRIPTION
**Pull request by matthewmcgarvey**
Fixes #2877
Related to #602

By returning params if `reason` is added to it and raising an exception if it's present, then we show an understandable error to users.

`7IpVsQVyok8` is a video that is age restricted.

<details>
<summary>Before</summary>
<br>

Screen Shot 2022-02-10 at 11 48 48 PM

</details>

<details>
<summary>After</summary>
<br>

Screen Shot 2022-02-10 at 11 46 23 PM

</details>

I noticed that while working with `7IpVsQVyok8` it would occasionally return as playable and then fail because it didn't return any related videos. I updated the code to not fail on that. It shows the video, but without related videos

<details>
<summary>Example</summary>
<br>

Screen Shot 2022-02-10 at 11 53 05 PM

</details>

<details>
<summary>Normal video just for reference</summary>
<br>

Screen Shot 2022-02-10 at 11 54 46 PM

</details>

### CODE REVIEW

**Review by SamantazFox — APPROVED** [review]
Looks good to me!

**Comment by unixfox** [comment]
in testing on https://yewtu.be

**Comment by SamantazFox** [comment]
@unixfox seems good?

**Comment by unixfox** [comment]
Seems like yes

**Pull request merged**
