### PR TITLE
Move "Projects using Invidious" section to the docs

### PR DESCRIPTION
**Pull request by syeopite**

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
@syeopite Can you do this instead: https://github.com/iv-org/invidious/pull/3853#issuecomment-1586150923

Basically move the list from the readme to the documentation (in "Applications) and just link to said documentation.

I forgot to do it, but I didn't plan to get the previous PR merged

**Comment by syeopite** [comment]
https://github.com/iv-org/documentation/pull/470

**Comment by maboroshin** [comment]
@syeopite : Thanks. This PL is fine. I understand FrenchGuy's plan.

**Comment by syeopite** [comment]
@TheFrenchGhosty good to merge?

**Review by TheFrenchGhosty — APPROVED** [review]

**Comment by TheFrenchGhosty** [comment]
@syeopite Good to merge now yes.

**Comment by SamantazFox** [comment]
I liked the fact that we advertised downstream projects in the readme.
But do as you like, tbh.

**Comment by TheFrenchGhosty** [comment]
@SamantazFox The problem is that it was messy to have 2 different list, it's a lot better to have one complete list in one place (and a more suitable one at that).

To have better recommendation, we should maybe mark some of them as "recommended" or "highly regarded" so that users don't have to choose one project in a list of dozens.

**Review by SamantazFox — APPROVED** [review]

**Comment by SamantazFox** [comment]
If that's ok for y'all, I can merge that in the next batch.
I hope to have some time free this weekend for that!

**Pull request merged**
