### PR TITLE
Rescue DB errors in get_video()

### PR DESCRIPTION
**Pull request by SamantazFox**
this should prevent the vast majority of issues related to DB problems.

### CODE REVIEW

**Comment by unixfox** [comment]
I can see this being an "infinite" loop if the DB is not reachable for a long time and thus consuming all the CPU.

**Comment by SamantazFox** [comment]
@unixfox How so? The `get_video()` function first tries to get the video the usual way (from the DB, check if it needs to be updated, fetch if required, and update entry) but if it encounters a DB error, it simply fetches the video info directly from innertube, and the DB is not touched again.

**Comment by unixfox** [comment]
Oops sorry, I reviewed the code late at night and I forgot that this function bypass postgresql.

**Comment by SamantazFox** [comment]
@unixfox no problem ^^ So it's good to merge, then?

**Review by unixfox — APPROVED** [review]

**Pull request merged**
