### PR TITLE
Modernize Logo

### PR DESCRIPTION
**Pull request by broquemonsieur**
victor

### CODE REVIEW

**Comment by unixfox** [comment]
Maybe put a preview image?

**Comment by acheong08** [comment]
The original looks more unique & original

**Comment by unixfox** [comment]
I personally prefer the original logo.

**Comment by TheFrenchGhosty** [comment]
ditto

**Comment by krim404** [comment]
the whitespace in the original logo seems to be intentional and serves important purposes for visual balance, readability, and brand consistency. the "new" one lacks it completly and make it look less professional.

**Pull request closed without merging**
