### PR TITLE
Add channel name to embeds

### PR DESCRIPTION
**Pull request by thecashewtrader**
Fairly trivial, and title is self explanatory, however there are some notes incase anyone wants to build on this idea:

There is an [existing issue](https://github.com/iv-org/invidious/issues/3251) that is related. However, so as to keep things separate, I made a separate PR.

The example video I am using is: https://youtube.com/watch?v=czCFyzTVDR8

Ideally I'd want to have the channel name in a separate (clickable) link like YouTube's embeds (Discord is used as an example):

image

However, the way YouTube does this seems a bit weird to me, and I'm not sure if this is OpenGraph compliant/compatible, so I decided to leave it out for the time being:
```html
<span itemprop="author" itemscope="" itemtype="http://schema.org/Person">
    <link itemprop="url" href="http://www.youtube.com/channel/UCz4a7agVFr1TxU-mpAP8hkw">
    <link itemprop="name" content="Soch by Mohak Mangal">
</span>
<script type="application/ld+json" nonce="c8LbRbPU2vjbBLiTESW1Tw">
    {"@context": "http://schema.org", "@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": 1, "item": {"@id": "http:\/\/www.youtube.com\/channel\/UCz4a7agVFr1TxU-mpAP8hkw", "name": "Soch by Mohak Mangal"}}]}
</script>
```

### CODE REVIEW

**Review by unixfox — APPROVED** [review]

**Comment by SamantazFox** [comment]
The problem I see with the `by <channel name>` being appended is that it won't play nicely with right-to-left titles and/or channel names, as well as non-english users.

> However, the way YouTube does this seems a bit weird to me, and I'm not sure if this is OpenGraph compliant/compatible, so I decided to leave it out for the time being:
> 
> ```
> <span itemprop="author" itemscope="" itemtype="http://schema.org/Person">
>     <link itemprop="url" href="http://www.youtube.com/channel/UCz4a7agVFr1TxU-mpAP8hkw">
>     <link itemprop="name" content="Soch by Mohak Mangal">
> </span>
> <script type="application/ld+json" nonce="c8LbRbPU2vjbBLiTESW1Tw">
>     {"@context": "http://schema.org", "@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": 1, "item": {"@id": "http:\/\/www.youtube.com\/channel\/UCz4a7agVFr1TxU-mpAP8hkw", "name": "Soch by Mohak Mangal"}}]}
> </script>
> ```

I'm pretty sure that this is done not by youtube but by discord.
None of the html `<meta ..>` tags that youtube returned contain the channel name.

**Comment by thecashewtrader** [comment]
I read up on OpenGraph a bit, what @SamantazFox said seems to be true.

Could we add the channel name to the `og:site_name` property like below? It seems a bit semantically suboptimal though.
```html
<meta property="og:site_name" content="Soch By Mohak Mangal | Invidious" />
```

**Comment by SamantazFox** [comment]
> Could we add the channel name to the `og:site_name` property like below? It seems a bit semantically suboptimal though.

I'm fine with that, though Idk if it's open graph compliant (it probably doesn't matter in the end, tho, as the "standard' constantly evolves depending on the tech giants' requirements)

**Comment by SamantazFox** [comment]
Thanks for your contribution :)

**Pull request merged**
