### PR TITLE
CSS: Remove inline styling of the download widget

### PR DESCRIPTION
**Pull request by jt0404**

### CODE REVIEW

**Comment by SamantazFox** [comment]
Can you please move that into the main CSS file please?
Adding an extra CSS file for 3 lines of text is not very efficient ^^

**Comment by jt0404** [comment]
You mean `default.css`?

**Comment by SamantazFox** [comment]
yes!

**Comment by jt0404** [comment]
done @SamantazFox !

**Review by SamantazFox — APPROVED** [review]

**Comment by SamantazFox** [comment]
Thanks for your contribution!

**Pull request merged**
