### PR TITLE
Remove freenode

### PR DESCRIPTION
**Pull request by Perflyst**
Reasons can be found in https://libera.chat/news/welcome-to-libera-chat

### CODE REVIEW

**Comment by Perflyst** [comment]
fyi @tmiland @SamantazFox @girst @comradekingu

**Comment by comradekingu** [comment]
I think having the channel registered (mentioning it has moved) is the better option.

**Comment by Perflyst** [comment]
Sadly, the xmpp <> matrix bridge is buggy

**Comment by comradekingu** [comment]
@Perflyst That is not a loss in my book.

**Comment by Perflyst** [comment]
IRC will be back soon, oftc or libera.chat or whatever else. Freenode got trashed yesterday. Please read https://libera.chat/news/welcome-to-libera-chat

**Comment by comradekingu** [comment]
Got removed from the organization. I have no dog in the race other than preferring XMPP (in a private capacity).

**Comment by comradekingu** [comment]
It would be possible to get freenode staff to help, provided one could demonstrate access to the repo (which I can't do anymore).
Not that I would, but alas.

@Perflyst 
Reading https://freenode.net/news/freenode-is-foss and accounting for donations needed to build an equivalent structure, or maintaining it, why is one option better than any other at this point?

**Comment by garoto** [comment]
Can't this wait till there's a Matrix <-> IRC bridge avaiable at libera.chat perhaps?

**Comment by garoto** [comment]
Just realized there's no one left on the freenode channel from Matrix. I have no idea who operates the protocol bridge or how it works, but was it disconnected on purpose?

**Comment by Perflyst** [comment]
The freenode bridge was disconnected as announced in the channel. You should drop your user from Freenode too.

**Comment by SamantazFox** [comment]
> sadly, the irc channel has no channel operator, so we can't set it to read-only, change the topic, ...

Yeah, Omar Roth is the only OP in there. @TheFrenchGhosty @Perflyst Do you think that you can contact him so he gives us OP access on IRC?

**Comment by SamantazFox** [comment]
> Just realized there's no one left on the freenode channel from Matrix. I have no idea who operates the protocol bridge or how it works, but was it disconnected on purpose?

The Matrix bridge is (well was) a joined effort between Matrix maintainers and Freenode staff.

**Comment by girst** [comment]
On Fri, May 21, 2021 at 05:30:22AM -0700, Samantaz Fox wrote:
>> sadly, the irc channel has no channel operator, so we can't set it to read-only, change the topic, ...
>
>Yeah, Omar Roth is the only OP in there. @TheFrenchGhosty @Perflyst Do you think that you can contact him so he gives us OP access on IRC?

that won't help. if he rejoins, he'll be a normal user too, until some 
chanop ops him too. which can't happen, since there are no ops left.  
our only recouse would be to contact freenode staff, i guess. but 
telling them "hey, we need your help getting rid of you" seems rude to 
me.

**Comment by garoto** [comment]
[**@Perflyst**](https://github.com/Perflyst) commented on [May 21, 2021, 3:06 AM GMT-3](https://github.com/iv-org/invidious/pull/2101?#issuecomment-845680155 "2021-05-21T06:06:15Z - Replied by Github Reply Comments"):
> The freenode bridge was disconnected as announced in the channel. You should drop your user from Freenode too.

Yeah my bad, just saw your message in the channel log telling so (somehow I missed it the 1st time in channel window itself). I told the remaining 27 IRC lurkers there that the channel was abandoned and /parted.

**Pull request merged**
