### PR TITLE
always show software

### PR DESCRIPTION
**Pull request by 706f6f7079646f6f646f6f**
makes it show the software in the error

send the money from #1690 to bitcoin:1Archive1n2C579dMsAu3iC6tWzuQJz8dN

### CODE REVIEW

**Comment by 706f6f7079646f6f646f6f** [comment]
like https://github.com/iv-org/invidious/blob/master/src/invidious/jobs/statistics_refresh_job.cr#L4 but only sofware

**Comment by SamantazFox** [comment]
Hello! Sorry to say that, but In the current state, your PR can't be merged.

The reason why we put a bounty on that PR is that it requires quite a bit of work to ensure that the JSON structure stays the same whenever the stats are enabled or not. This also implies that this endpoint should never return an error, and instead indicate, by some boolean value or some status message, that the stats are disabled.

**Comment by 706f6f7079646f6f646f6f** [comment]
like this maybe?

**Comment by 706f6f7079646f6f646f6f** [comment]
@SamantazFox no good? why not? structure is always good now and status now too

**Comment by syeopite** [comment]
Lack of an review doesn't mean the PR isn't "good". We're quite busy! Please have some patience until one of us gets to reviewing it :)

**Comment by 706f6f7079646f6f646f6f** [comment]
ok i wait

**Comment by 706f6f7079646f6f646f6f** [comment]
💩💩💩💩💩💩💩💩💩💩💩

**Comment by 706f6f7079646f6f646f6f** [comment]
BOUNTY but NO REVIEW

fucking RETACULOUS

so important YOU PAY MONEY - then NO MEREGE

@unixfox @TheFrenchGhosty @SamantazFox @syeopite @saltycrys @invidious-bot

**Comment by TheFrenchGhosty** [comment]
@706f6f7079646f6f646f6f We don't owe you anything.

The team is busy so be patient.

**Pull request closed without merging**
