### PR TITLE
fix: ytInitialData parsing with regex

### PR DESCRIPTION
**Pull request by tirz**
Fix https://github.com/iv-org/invidious/issues/1488

The issue was that our regex checked for spaces / new lines after `;`.
But by fixing this issue, we may break others parsing... (tested manually since I did not found any unit test)
So we have to enforce the regex to parse only between the brackets `{...}` and everything works fine \o/ !

Also remove the legacy code:
```
if initial_data.starts_with?("JSON.parse(\"")
```
Since it will always be false (because of `{...}`).

### CODE REVIEW

**Comment by hackerncoder** [comment]
This PR is up for testing on https://vid.encryptionin.space

**Comment by saltycrys** [comment]
I like this approach better than mine. It makes the code more resistant to future YouTube changes.

I found that the JSON chunk can contain newlines, this can be fixed with the `m` flag. Also your regex currently doesn't match if `JSON.parse` is present.

How about this regex:
```regex
/(window\["ytInitialData"\]|var\s*ytInitialData)\s*=\s*(JSON\.parse\(")?(?<info>\{.*?\})("\))?;/m
```

I also took this opportunity to move all `ytInitialData` parsing to the `extract_initial_data` helper function, see https://github.com/iv-org/invidious/pull/1491/commits/9ea20cca322ddf777b6f1194a88abfec27113686. If you want you can include this here.

**Comment by tirz** [comment]
https://github.com/iv-org/invidious/commit/9ea20cca322ddf777b6f1194a88abfec27113686 is interesting. I will add it.

I got some errors if we do not enforce the brackets, so `{.*?\}` is mandatory.
About `JSON.parse("`, are you sure that this is still in used?

**Comment by tirz** [comment]
@saltycrys I did like https://github.com/iv-org/invidious/commit/9ea20cca322ddf777b6f1194a88abfec27113686 with a little difference.

I changed:

```
  initdata_pre = about.body.index(INITDATA_PREQUERY)
  initdata_post = initdata_pre.nil? ? nil : about.body.index("};", initdata_pre)
  if initdata_post.nil?
    about = XML.parse_html(about.body)
    error_message = about.xpath_node(%q(//div[@class="yt-alert-content"])).try &.content.strip
    error_message ||= translate(locale, "Could not get channel info.")
    raise error_message
  end
  initdata_pre = initdata_pre.not_nil! + INITDATA_PREQUERY.size - 1

  initdata = JSON.parse(about.body[initdata_pre, initdata_post - initdata_pre + 1])
  about = XML.parse_html(about.body)

  if about.xpath_node(%q(//div[contains(@class, "channel-empty-message")]))
    error_message = translate(locale, "This channel does not exist.")
    raise error_message
  end
```

to:

```
  about = XML.parse_html(result.body)
  if about.xpath_node(%q(//div[contains(@class, "channel-empty-message")]))
    error_message = translate(locale, "This channel does not exist.")
    raise error_message
  end

  initdata = extract_initial_data(result.body)
  if initdata.empty?
    error_message = about.xpath_node(%q(//div[@class="yt-alert-content"])).try &.content.strip
    error_message ||= translate(locale, "Could not get channel info.")
    raise error_message
  end
```

Note the reverse order of `if initdata_post.nil?` and `if about.xpath_node(%q(//div[contains(@class, "channel-empty-message")]))` - also note that the value `about` was sometime renamed `result` since they was really different values with different type !

In sum up:
 - the xml `about` was shadowing the the string `about` (not the same type)
 - we were checking if the channel data was parse-able before checking if the channel really exist

**Comment by hackerncoder** [comment]
The newest commit to this PR is up for testing on https://vid.encryptionin.space

**Comment by saltycrys** [comment]
Looks good, `INITDATA_PREQUERY` can now be removed from `src/invidious/channels.cr`.

About `JSON.parse`: I've never seen it but better safe than sorry. What I have seen is newlines in the JSON chunk, so the `m` flag should be added to enable dots matching newlines. So `/[regex]/m`.

**Comment by tirz** [comment]
- Used value `INITDATA_PREQUERY` removed.
 - `/[regex]/m` was already handled since this patch parse everything between `{...}` (and ending by `;`), the new line feed `\n` included. But I added it anyway, it will allow us to remove the strict `{...}` if `JSON.parse` is really needed.
 - I have some doubt about adding `JSON.parse` back since it look like an outdated code and their is no need to maintain it.

**Comment by hackerncoder** [comment]
I finally got the newest commit to this PR is up for testing on https://vid.encryptionin.space

**Comment by saltycrys** [comment]
The dot does not match newlines by default in PCRE (Perl Compatible Regular Expressions, the regex library Crystal uses).

You can try it yourself:
```shell
$ crystal eval 'puts "a\nb".match(/a.*b/).nil?; puts "a\nb".match(/a.*b/m)'
true
Regex::MatchData("a\nb")
```

I think `JSON.parse` should be included, but it's up to the maintainers.

I propose this regex for `JSON.parse` support:
```regex
/(window\["ytInitialData"\]|var\s*ytInitialData)\s*=\s*(JSON\.parse\(")?(?<info>\{.*?\})("\))?;/m
```
which is your regex:
```regex
/(window\["ytInitialData"\]|var\s*ytInitialData)\s*=\s*(?<info>\{.*?\});/m
```
with the info group wrapped in `(JSON\.parse\(")?` and `("\))?`.

**Comment by saltycrys** [comment]
I'd like to have `JSON.parse` supported because it's the safer choice.

Best case: YouTube uses `JSON.parse` again and Invidious does not break and does not need to be updated.
Worst case: YouTube never uses `JSON.parse` again and Invidious has some unneeded code.

**Comment by saltycrys** [comment]
I really like your simplification of `extract_initial_data` and just meant to include `JSON.parse` with it. Sorry about the confusion.

What I meant was:
```crystal
def extract_initial_data(body) : Hash(String, JSON::Any)
  return JSON.parse(body.match(/(window\["ytInitialData"\]|var\s*ytInitialData)\s*=\s*(JSON\.parse\(")?(?<info>\{.*?\})("\))?;/m).try &.["info"] || "{}").as_h
end
```

The info group will have all of the JSON in any case without any special handling. No matter what follows after the data because the brackets take care of it.

**Comment by TheFrenchGhosty** [comment]
PR has been tested and seems to be working, but there's one massive issue: the search results are the same on every page (tested with the search "ltt").

**Comment by hackerncoder** [comment]
> PR has been tested and seems to be working, but there's one massive issue: the search results are the same on every page (tested with the search "ltt" and "pewdiepie").

Hasn't this been a problem for some time?

**Comment by TheFrenchGhosty** [comment]
@hackerncoder 

>Hasn't this been a problem for some time?

I actually wasn't aware of that, but looks like you're right #1480

**Comment by B0pol** [comment]
@TheFrenchGhosty it's an unrelated issue: #1480

**Comment by tirz** [comment]
@saltycrys I reverted part of my revert :p
So `extract_initial_data` is a one liner with `JSON.parse("` on is regex.

@TheFrenchGhosty yes, I was trying to find this issue (https://github.com/iv-org/invidious/issues/1480).
This bug is another bug not related to the parsing of the regex :/

**Comment by TheFrenchGhosty** [comment]
Should I merge it even with this issue?

**Comment by hackerncoder** [comment]
@TheFrenchGhosty Yes, at least let us have some search.

**Comment by tirz** [comment]
@TheFrenchGhosty yes you can, https://github.com/iv-org/invidious/issues/1480 need another PR with a totally different fix.

**Comment by tirz** [comment]
@saltycrys ?

**Comment by TheFrenchGhosty** [comment]
I'm merging this then, if you @saltycrys think it can be enhanced, feel free to open another PR.

**Comment by saltycrys** [comment]
It cannot be enhanced, it is a fantastic one liner that solves all of our `ytInitialData` problems.

Well done @tirz and thank you!

**Comment by TheFrenchGhosty** [comment]
@saltycrys Amazing then!

Big thanks to both you @saltycrys @tirz !

**Comment by cy8aer** [comment]
Unfortunatelly with this patch no channel searching does not work anymore: Nil assertion failed

**Comment by hackerncoder** [comment]
@cy8aer like this: https://vid.encryptionin.space/channel/UC3swwxiALG5c0Tvom83tPGg ?

**Comment by cy8aer** [comment]
More like this:

grafik

**Comment by cy8aer** [comment]
@hackerncoder If you mean the type of url: yes this type (sorry).

**Comment by hackerncoder** [comment]
@Perflyst 

Commit b41ca72d2b85c8d6ee5186873bf4be4c331e3798 failed in travis.

My server running 1ba17a0e148b7cb52b34d756c945f5d8976b9913 is working fine, but the one @cy8aer is using which is running 99ba9874b11bb0a5b67854d338ce968e83c69c41 isn't.

**Comment by hackerncoder** [comment]
This doesn't make any sense? I just updated to 99ba987 and mine is working fine, yet other instances don't work????

**Comment by cy8aer** [comment]
My instance is vanilla. Are there are other factors that let this problem occur? With b41ca72d2b85c8 it worked fine.

**Comment by tirz** [comment]
Interesting...
I tried to reproduce the issue on https://vid.encryptionin.space/ and https://invidious.snopyta.org/ : both of them updated to https://github.com/iv-org/invidious/commit/99ba9874b11bb0a5b67854d338ce968e83c69c41 but with no luck.
Everything is worked fine on my side :/
@cy8aer does the bug appear periodically?
Do you have a special case which may trigger the `Nil assertion failed`?
And does it affect ONLY the channels?

**Comment by cy8aer** [comment]
It is only and all channels.

**Comment by hackerncoder** [comment]
I seem to be able to reproduce this on all other instance, just not mine.

**Comment by tirz** [comment]
https://github.com/iv-org/invidious/commit/b41ca72d2b85c8d6ee5186873bf4be4c331e3798 and https://github.com/iv-org/invidious/commit/99ba9874b11bb0a5b67854d338ce968e83c69c41 runs the sames code ^^'
It is one commit and one merge from 2 different person but with the same content... So I guess the bug is running periodically on the channels :/

**Comment by cy8aer** [comment]
Hm, switched my instance from ipv4 to ipv6. Now it works. Looks like a local blocking.

**Pull request merged**
