### PR TITLE
Fix proxy throttling

### LINKED ISSUE #3619: [Bug] Proxying is disabled entirely when only allowing downloads.
having set the 
```yaml
disable_proxy:
         - local
         - livestreams
         - dash
```
in the `docker-compose.yml` file causes dash streams and proxied video to be disabled but it also disables downloads.
The download button is there but upon clicking on it, it redirects to a page saying `Administrator has disabled this endpoint.`
brave_vpfHSWgFQC
brave_oUG9AfJy3V

### LINKED ISSUE #3666: [Bug] Slow loading time with DASH
**Describe the bug**
I recently noticed that DASH will always be showing the lowest quality. 
This looks consistent across instances and videos.
I thought it was my internet, but it's not.

**Steps to Reproduce**
1. Preferred video quality: DASH
2. Preferred DASH video quality: auto
3. Open any video
4. The quality will be lowest (like 144p) and does not improve

**More context**
Both Invidious player and [Playlet](https://github.com/iBicha/playlet) are seeing the same thing (low quality DASH)

### PR DESCRIPTION
**Pull request by SamantazFox**
Closes #3666
Closes #3619

### CODE REVIEW

**Comment by unixfox** [comment]
Is this fully deployed on https://test.invidious.io?

**Review by unixfox — APPROVED** [review]
Seems to work fine on the test instance. Did a couple of tests.

**Comment by SamantazFox** [comment]
I've redeployed the PR to be sure, and I have issues with DASH.
I think I changed something and forgot to commit :/

**Comment by unixfox** [comment]
Let me know when I can test again.

**Comment by LennyPenny** [comment]
I also tried some videos that were very slow to load on my instance vs the testing one and can confirm it working nicely!

**Comment by Zero3K** [comment]
It doesn't work with -8slMvu2T-k on the test instance.

**Comment by SamantazFox** [comment]
Not relevant anymore with inv_sig_helper

**Pull request closed without merging**
