### PR TITLE
Add meta tags to channels

### PR DESCRIPTION
**Pull request by thecashewtrader**
A note: this commit uses the same suspended username mentioned in #3346.

### CODE REVIEW

**Comment by SamantazFox** [comment]
Is `twitter:site` really needed? As you mentioned, the username used here doesn't exist anymore, so we don't have anything to replace it.

**Comment by thecashewtrader** [comment]
According to [this document](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup), it is required, though it can be argued it's not consequential.
Anyway, https://twitter.com/iv-org is free for now, so could we take it and just put that here?

**Comment by TheFrenchGhosty** [comment]
Discussed internally: I have no desire for us to ever get a Twitter account, if possible, removing all the lines related to "our" account is the way to go.

**Comment by thecashewtrader** [comment]
Aight, fair enough.

**Review by SamantazFox — APPROVED** [review]

**Comment by SamantazFox** [comment]
Thanks for your contribution to invidious!

**Pull request merged**
