### PR TITLE
API: Fix error code for disabled popular endpoint

### PR DESCRIPTION
**Pull request by iBicha**
When visiting /api/v1/popular and popular endpoint is disabled
Before:
```
500 {"error":"Closed stream"}
```
After
```
403 {"error":"Administrator has disabled this endpoint."}
```

### CODE REVIEW

**Review by SamantazFox — APPROVED** [review]

**Comment by iBicha** [comment]
Bump

**Comment by iBicha** [comment]
I don't know what changed, but /api/v1/popular now returns 
```
400 {"error":"Administrator has disabled this endpoint."}
```
Closing

**Comment by syeopite** [comment]
The PR should probably still be kept to change the HTTP status code from 400 to 403.

The former doesn't exactly fit for a disabled endpoint

**Comment by iBicha** [comment]
> The PR should probably still be kept to change the HTTP status code from 400 to 403.
> 
> The former doesn't exactly fit for a disabled endpoint

Fair - updated PR

**Review by NorkzYT — APPROVED** [review]

**Comment by SamantazFox** [comment]
Thanks for the fix!

**Comment by NorkzYT** [comment]
No problem. Thank you for merging.

**Pull request merged**
