### PR TITLE
README: Improve "Projects using Invidious" section

### PR DESCRIPTION
**Pull request by maboroshin**
Add target devices to each app (Android/Online, etc.). So the text is almost identical. 

Change the order of the listings. Move up Clipious and yattee, which are currently available and in active development. It appears multi-features and the large number of devices covered.

Changes are reflected:

* Holoplay : GitHub repository name is maybe broken. It's working now. Move up because it is fast available online.
* WatchTube : GitHub repository name has changed. A recent version is available in the App Store.
* CloudTube : Move down a bit, because search is not working (JSON Error) in https://tube.cadence.moe/. There are recent commits.

Stalled projects: Moved down in the list:

* MusicPiped : Stopped in March 2022. Developer is not working on it. See the issue: https://github.com/deep-gaurav/MusicPiped/issues/146#issuecomment-1053810522
* PeerTubeify : Commented out. https://gitlab.com/Cha_de_L/peertubeify : Last change of the repository in 2020. Official site (https://peertube.video/) is other site now.

----
(18 July 2023: Added 2 applications for Linux.)
* GTK+ Pipe Viewer : Many features.
* PlasmaTube : Early development state. But one of KDE.

----
(24 July 2023: Note)
* [Muer](https://github.com/muer-org/muer) is new online frontend.

Can login and sync: Clipious, yattee, PlasmaTube

### CODE REVIEW

**Comment by SethFalco** [comment]
Is there meant to be any notable difference between this list and the one on docs.invidious.io? The only item they have in common in Playlet. :thinking: 

https://docs.invidious.io/applications/

Wondering if maybe the README should only show a few highlights from either list, then direct the user to this page instead so it's all in one place?

**Comment by TheFrenchGhosty** [comment]
@SethFalco I've been planning to deprecate the list in the README for month to move everything to a (better) list in the documentation, I've just been busy/lazy.

**Comment by maboroshin** [comment]
@SethFalco The list SethFalco mentioned has absolutely nothing to do with README.md.

* README.md
* * List of applications using the Invidious API.

* docs.invidious.io/applications/
* * Most are browser extensions or user scripts called redirectors. To forward YouTube URLs to Inbvidious.
* * Playlet is the only app that uses Invidious.
* * This list include related Apps like SponsorBlock.

**Comment by TheFrenchGhosty** [comment]
@maboroshin @SethFalco That's the point. There should only be a single list with everything.

**Comment by maboroshin** [comment]
Only Playlet and Privacy Redirect are duplicated between docs.invidious.io and README.md

Updating docs.invidious.io : https://github.com/iv-org/documentation/pull/407

**Comment by SamantazFox** [comment]
Sorry for the delay reviewing this! Can you rebase your changes, please? (If you don't know how to do that, I can do it).

**Comment by maboroshin** [comment]
@SamantazFox I don't understand rebase. In Gitlab, it could be executed with one click from the web.

**Comment by unixfox** [comment]
@maboroshin can you rebase the PR?

@TheFrenchGhosty please check if everything is ok here

**Comment by maboroshin** [comment]
@unixfox : https://github.com/iv-org/invidious/pull/3853#issuecomment-1636790954

**Comment by unixfox** [comment]
> @unixfox : https://github.com/iv-org/invidious/pull/3853#issuecomment-1636790954

https://www.simplilearn.com/what-is-git-rebase-command-article
https://docs.github.com/en/get-started/using-git/using-git-rebase-on-the-command-line

Look on the internet how to do it :)

**Comment by maboroshin** [comment]
Many commands are found. I don't know which one is appropriate.

SamantazFox said:
> If you don't know how to do that, I can do it

**Comment by syeopite** [comment]
Oops. I was trying to rebase this PR but ended up pushing my master branch instead of the rebased branch to your fork 😅

**Comment by maboroshin** [comment]
Thanks for continuing. OK, no problem.

**Pull request closed without merging**
