### PR TITLE
Automate monthly release

### PR DESCRIPTION
**Pull request by hackerncoder**
This is for #1756.

Every 25th of the month, a new branch is created, for feature freeze. Then on the first a new tag is made from the status at that time on that branch.

Fixes should be backported (right word?) from master to the next release in that week.

### CODE REVIEW

**Comment by hackerncoder** [comment]
Marking as draft as I have two things I want to do: Make the tag better (probably show a list of commits) and figure out what to do with the branches, currently they'll just pile up.

**Comment by TheFrenchGhosty** [comment]
Why branches and not just tags?

**Comment by hackerncoder** [comment]
Feature freeze where fixes can be applied. As the original issue stated:

> A week prior to the release, only fixes would be accepted in master to avoid introducing last-minute changes that might create issues and let instances based on master report issues and bug that would be high priority.

I thought it should happen in a different branch. If you think that is wrong, do tell me.

**Review by syeopite — CHANGES_REQUESTED** [review]
Please standardize the indents to two spaces like all of the other workflow files.

**Review by syeopite — APPROVED** [review]
Looks good to me. The whole branches vs tags things needs to be discussed however but for now, assuming we're sticking with branches, could you maybe add something to automatically delete feature freeze branches older than say 5 months? If we don't have something to automatically remove those ancient versions then the branch tree is going to get cluttered fast.

**Comment by syeopite** [comment]
Also, could you limit the amount of force pushes you're doing? We should be able to reduce this PR into one commit via the merge and squash version on GitHub anyways.

**Comment by hackerncoder** [comment]
> Looks good to me. The whole branches vs tags things needs to be discussed however but for now, assuming we're sticking with branches, could you maybe add something to automatically delete feature freeze branches older than say 5 months? If we don't have something to automatically remove those ancient versions then the branch tree is going to get cluttered fast.

Done.

> Also, could you limit the amount of force pushes you're doing? We should be able to reduce this PR into one commit via the merge and squash version on GitHub anyways.

Alright.

**Comment by SamantazFox** [comment]
Quick remark: wouldn't bi-monthly be better? We're doing a lot of merges, especially recently, so "last month" release is going to be pretty old at some point.

**Comment by hackerncoder** [comment]
And wouldn't bi-monthly be even more outdated?

**Review by TheFrenchGhosty — CHANGES_REQUESTED** [review]
Okay, so I finally got around to reviewing this PR.

>Every 25th of the month

Why the 25th? Why not the 30th? Why not the 1st? Why an arbitrary "25th"?

>a new branch is created, for feature freeze. Then on the first a new tag is made from the status at that time on that branch.

... why have a branch on the 25th and a release on the 1st, what's the point, why not just have a release on the 1st? If I understand correctly you want us to maintain an outdated version with fixes... for 1 month? What's the point?

>Fixes should be backported (right word?) from master to the next release in that week.

We're not maintaining an outdated version.

>and figure out what to do with the branches, currently they'll just pile up.

Don't have branches, because they are completely useless.

>Feature freeze where fixes can be applied.

No, invidious won't have a branch that don't get features but just fixes. It's useless micromanagement for something completely useless.

And to add to that: Invidious works in a rolling release model, we didn't need releases, there isn't any point in it in my opinion... other than major version bump for breaking changes... but since it's currently using a date-based release name it's won't work.

**Comment by TheFrenchGhosty** [comment]
@hackerncoder No need to close it, releases are a *maybe* (surely) a good idea (like I said for "major version bump for breaking changes") but it mustn't add more micromanagement, and from what I can see https://github.com/hackerncoder/invidious/releases/tag/2021.07.01 it works correctly, and can be used as a base for a "normal" version numbering.

PS: I know my review was a bit "agressive", I went to the point because I really don't understand the *why* most of it is needed, however please, don't dump all this work.

**Comment by hackerncoder** [comment]
As it is currently, this PR is crap. If you want automated releases, I'll do it, but I don't think it should be based on a schedule (per your review).

> but since it's currently using a date-based release name it's won't work.

I'll also need to know how you want the release name to be.

----

Why: I implemented the issue #1756 + my own thoughts. 

> Why the 25th? Why not the 30th? Why not the 1st? Why an arbitrary "25th"?

"(was supposed to be 23, no idea why I used 25)" because "A week prior to the release, only fixes would be accepted in master to avoid introducing last-minute changes that might create issues and let instances based on master report issues and bug that would be high priority."

> for 1 month?

"in that week"

**Comment by TheFrenchGhosty** [comment]
@hackerncoder 

For the release name I guess 1.XX, and if there's breaking change we bump to 2.XX (though a bump to 2.00 might look more than what it actually is, we need to discuss it) - for an example of software that does it that way (kinda) see [Komga](https://github.com/gotson/komga/releases)

>"(was supposed to be 23, no idea why I used 25)" because "A week prior to the release, only fixes would be accepted in master to avoid introducing last-minute changes that might create issues and let instances based on master report issues and bug that would be high priority."

Yeah, it really doesn't work for Invidious.

**Comment by saltycrys** [comment]
Invidious currently uses date based versions: https://github.com/iv-org/invidious/blob/5a8825d01682def020acfd2baf95a44b94790f6f/src/invidious.cr#L55

**Comment by SamantazFox** [comment]
bump

**Comment by hackerncoder** [comment]
I am leaving the organization and cleaning up stuff.

**Pull request closed without merging**
