### PR TITLE
Remove dislikes icon

### PR DESCRIPTION
**Pull request by unixfox**
Change only on the frontend side for the moment.

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
The plan was to only hide it from the frontend so that addons could "restore" the frontend code "easily".

**Comment by unixfox** [comment]
Addons can inject code into the page too.

I don't see the point of keeping it in the code. Moreover accessibility wise it's not great to still have the text and icon in the code but visually hiden.

**Comment by TheFrenchGhosty** [comment]
It was @SamantazFox plan, so I'll let her answer.

>Moreover accessibility wise it's not great to still have the text and icon in the code but visually hiden.

It was planed to be commented out in the HTML.

**Comment by unixfox** [comment]
> > 
> 
> 
> 
> > Addons can inject HTML code into the page too.
> > 
> > I don't see the point of keeping it in the HTML page.
> > 
> > Moreover accessibility wise it's not great to still have the text and icon in the html code but visually hidden.
> 
> My idea was to only keep `<p id="dislikes"></p>`, so that add-ons can select the HTML element based using its id and fill the content.

Do I do that then?

**Comment by TheFrenchGhosty** [comment]
>Do I do that then?

Yes

**Comment by unixfox** [comment]
Done, ready to review.

**Comment by unixfox** [comment]
I merged the change because we all agreed on keeping to the solution in https://github.com/iv-org/invidious/pull/3092#issuecomment-1122790432

**Pull request merged**
