### PR TITLE
API: Unescape search suggestions

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
Related: https://github.com/FreeTubeApp/FreeTube/pull/4261

Currently, search suggestions are html encoded, this PR decodes the suggestions.

test url: /api/v1/search/suggestions/?q=%D8%AA%D9%81

with this PR:
```json
{"query":"تف","suggestions":["تفسير سورة البقرة","تفضلوا على العشاء","تفحيط","تفداك عيني ومالي وامي وابوي وعيالي كاملة","تفنن","تفجيرات السمارة","تفسير القران","تفو تفو عليك","تفسير سورة الكهف","تفاح الحرام","تفسير الاحلام","تفيد بايه يا ندم ام كلثوم","تفسير سورة الاسراء"]}
```

without this PR:
```json
{"query":"&#1578;&#1601;","suggestions":["&#1578;&#1601;&#1587;&#1610;&#1585; &#1587;&#1608;&#1585;&#1577; &#1575;&#1604;&#1576;&#1602;&#1585;&#1577;","&#1578;&#1601;&#1590;&#1604;&#1608;&#1575; &#1593;&#1604;&#1609; &#1575;&#1604;&#1593;&#1588;&#1575;&#1569;","&#1578;&#1601;&#1581;&#1610;&#1591;","&#1578;&#1601;&#1606;&#1606;","&#1578;&#1601;&#1583;&#1575;&#1603; &#1593;&#1610;&#1606;&#1610; &#1608;&#1605;&#1575;&#1604;&#1610; &#1608;&#1575;&#1605;&#1610; &#1608;&#1575;&#1576;&#1608;&#1610; &#1608;&#1593;&#1610;&#1575;&#1604;&#1610; &#1603;&#1575;&#1605;&#1604;&#1577;","&#1578;&#1601;&#1580;&#1610;&#1585;&#1575;&#1578; &#1575;&#1604;&#1587;&#1605;&#1575;&#1585;&#1577;","&#1578;&#1601;&#1587;&#1610;&#1585; &#1575;&#1604;&#1602;&#1585;&#1575;&#1606;","&#1578;&#1601;&#1608; &#1578;&#1601;&#1608; &#1593;&#1604;&#1610;&#1603;","&#1578;&#1601;&#1587;&#1610;&#1585; &#1587;&#1608;&#1585;&#1577; &#1575;&#1604;&#1603;&#1607;&#1601;","&#1578;&#1601;&#1575;&#1581; &#1575;&#1604;&#1581;&#1585;&#1575;&#1605;","&#1578;&#1601;&#1587;&#1610;&#1585; &#1575;&#1604;&#1575;&#1581;&#1604;&#1575;&#1605;","&#1578;&#1601;&#1610;&#1583; &#1576;&#1575;&#1610;&#1607; &#1610;&#1575; &#1606;&#1583;&#1605; &#1575;&#1605; &#1603;&#1604;&#1579;&#1608;&#1605;","&#1578;&#1601;&#1587;&#1610;&#1585; &#1587;&#1608;&#1585;&#1577; &#1575;&#1604;&#1575;&#1587;&#1585;&#1575;&#1569;"]}
```

### CODE REVIEW

**Comment by syeopite** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/4261#issuecomment-1787628986

https://github.com/iv-org/invidious/blob/d7285992517c98a276e325f83e1b7584dac3c498/src/invidious/routes/api/v1/search.cr#L34-L40

It doesn't look like Invidious is escaping it, or at least not directly. Is Invidious utilizing a query that causes YouTube to return escaped queries?

**Comment by ChunkyProgrammer** [comment]
> It doesn't look like Invidious is escaping it, or at least not directly. Is Invidious utilizing a query that causes YouTube to return escaped queries?

Running this query directly: 
https://suggestqueries-clients6.youtube.com/complete/search?client=youtube&hl=en&gl=US&q=%D8%AA%D9%81&xssi=t&gs_ri=youtube&ds=yt
has no issues and displays the Arabic correctly. I will investigate more in case there's a better solution

**Comment by ChunkyProgrammer** [comment]
I couldn't find any clear cause of the issue (it might be a crystal issue?) but this PR does fix the issue

**Comment by absidue** [comment]
Have you tried adding some logging around these lines to see what the URL looks like, what the raw response from YouTube looks like etc?
https://github.com/iv-org/invidious/blob/d7285992517c98a276e325f83e1b7584dac3c498/src/invidious/routes/api/v1/search.cr#L34-L40

**Comment by SamantazFox** [comment]
What if you remove `&xssi=t` from here?

https://github.com/iv-org/invidious/blob/9ce9c543992243737516750bf08f5d073e899715/src/invidious/routes/api/v1/search.cr#L35

**Comment by ChunkyProgrammer** [comment]
> What if you remove `&xssi=t` from here?
> 
> https://github.com/iv-org/invidious/blob/9ce9c543992243737516750bf08f5d073e899715/src/invidious/routes/api/v1/search.cr#L35

Removing the `&xssti=t` returns a weird unicode response instead
```javascript
window.google.ac.h(["\u062A\u0641",[["\u062A\u0641\u0633\u064A\u0631 \u0633\u0648\u0631\u0629 \u0627\u0644\u0628\u0642\u0631\u0629",0,[512,433]],["\u062A\u0641\u0633\u064A\u0631 \u0627\u064A\u0629 \u0627\u0644\u0643\u0631\u0633\u064A",0,[512,650,433,131]],["\u062A\u0641\u0636\u0644\u0648\u0627 \u0639\u0644\u0649 \u0627\u0644\u0639\u0634\u0627\u0621",0,[512]],["\u062A\u0641\u062D\u064A\u0637",0,[512,433]],["\u062A\u0641\u0646\u0646",0,[512]],["\u062A\u0641\u062F\u0627\u0643 \u0639\u064A\u0646\u064A \u0648\u0645\u0627\u0644\u064A \u0648\u0627\u0645\u064A \u0648\u0627\u0628\u0648\u064A \u0648\u0639\u064A\u0627\u0644\u064A \u0643\u0627\u0645\u0644\u0629",0,[512]],["\u062A\u0641\u0633\u064A\u0631 \u0627\u0644\u0642\u0631\u0627\u0646",0,[512,433]],["\u062A\u0641\u0648 \u062A\u0641\u0648 \u0639\u0644\u064A\u0643",0,[512]],["\u062A\u0641\u0633\u064A\u0631 \u0633\u0648\u0631\u0629 \u0627\u0644\u0643\u0647\u0641",0,[512]],["\u062A\u0641\u0633\u064A\u0631 \u0627\u0644\u0627\u062D\u0644\u0627\u0645",0,[512,433]],["\u062A\u0641\u0627\u062D \u0627\u0644\u062D\u0631\u0627\u0645",0,[512,433]],["\u062A\u0641\u064A\u062F \u0628\u0627\u064A\u0647 \u064A\u0627 \u0646\u062F\u0645 \u0627\u0645 \u0643\u0644\u062B\u0648\u0645",0,[512]],["\u062A\u0641\u0633\u064A\u0631 \u0633\u0648\u0631\u0629 \u0627\u0644\u0641\u0627\u062A\u062D\u0629",0,[512]],["\u062A\u0641\u0631\u06CC\u0642",0,[512]]],{"k":1,"q":"E7u28fSXROWBKbNM3e-ymGw0asE"}])
```

**Comment by absidue** [comment]
Those are fine, if you copy paste that string as is and stick is in console.log, you'll notice that it parses those unicode codepoints

**Review by SamantazFox — APPROVED** [review]

**Review by SamantazFox — APPROVED** [review]

**Pull request merged**
