### PR TITLE
Improve logging

### LINKED ISSUE #385: Configure Log level
Add an option to set the log level. For example I do not want `GET` request logged.
Maybe following log levels:
Error, Warn, (Normal / Default), Debug

I do not know if there are already any debug logs which you may use somewhere for testing, if not just drop debug.

### PR DESCRIPTION
**Pull request by saltycrys**
Everything that gets logged now has a log level associated with it.

The log level can be set with the new `-l` or `--log-level` arguments.

The defaul log level is `debug` for now. There aren't many things that get
logged but if the logs get spammed in the future it can be set down to `info`.

Closes #385

### CODE REVIEW

**Comment by Perflyst** [comment]
Closes #385

**Comment by saltycrys** [comment]
@Perflyst do you want me to set the default log level to `warn` instead? That wouldn't print requests.

**Comment by Perflyst** [comment]
No, if debug matches the current logging debug by default is fine.

**Comment by GauthierPLM** [comment]
This is a good improvement. Paired with more verbose logging (more informations returned), we could use that to improve the reliability of Invidious instances and finally solve these "Video not available" errors.

**Pull request merged**
