### PR TITLE
Add hmacKeyConfigured field to stats api

### PR DESCRIPTION
**Pull request by iBicha**
see #3540

### CODE REVIEW

**Comment by unixfox** [comment]
Can you post the results of the API?

**Comment by iBicha** [comment]
> Can you post the results of the API?

```
{
   "version":"2.0",
   "software":{
      "name":"invidious",
      "version":"2023.05.30-b56e55c8",
      "branch":"feature/hmac-key-check"
   },
   "openRegistrations":true,
   "usage":{
      "users":{
         "total":7,
         "activeHalfyear":7,
         "activeMonth":0
      }
   },
   "metadata":{
      "updatedAt":1685484461,
      "lastChannelRefreshedAt":1685467825,
      "hmacKeyConfigured":true
   }
}
```

**Comment by SamantazFox** [comment]
I'd rather have a startup check for this config that prevents invidious from running if not set.
The docs should also be updated to shown a sample value in the example config/compose files, like Searx does:

https://github.com/searxng/searxng-docker/blob/e76656a162c40c04ecc4b119d2a28ec2104c5275/searxng/settings.yml#L3-L7

**Comment by unixfox** [comment]
> I'd rather have a startup check for this config that prevents invidious from running if not set.
> The docs should also be updated to shown a sample value in the example config/compose files, like Searx does:
> 
> https://github.com/searxng/searxng-docker/blob/e76656a162c40c04ecc4b119d2a28ec2104c5275/searxng/settings.yml#L3-L7
> 

Do you understand that this will temporarily break thousands of existing installations?

I'm also in favor of this way but that's quite disruptive to do that right now.

**Comment by SamantazFox** [comment]
@iBicha what's your original motivation behind this PR?
Is it because you're having issues on playlet with public instances?

> Do you understand that this will temporarily break thousands of existing installations?

Yes, I'm aware. Usually, I try to always make changes that won't hard break invidious, but I've been thinking about adding back semantic versioning and starting to make some heavier changes (That could deserve a separate issue, tho).

Regarding this specific PR, I'd like to take the opportunity to remove an entry from the FAQ, too.
We had many users complaining about the broken authentication in the past, so by making the hmac key mandatory, we could ensure that instances don't give a bad user experience because of misconfiguration.

**Comment by iBicha** [comment]
> @iBicha what's your original motivation behind this PR? Is it because you're having issues on playlet with public instances?

Yes, for Playlet. Unconfigured key causes the tokens to invalidate somewhat randomly, and leaves people confused because there's no indication on why. It also affects the /authorize part. It takes a few retries to get a valid token in the first place.

I totally agree with you, this needs to be a startup check, with a clear error message on what was wrong.
Although disruptive, have Invidious failing to start will get the attention of maintainers and get them to fix this necessary config, and it's a one time thing.

If we really want to go through the less disruptive route, my original idea in #3540 is to cache if hmac_key between restarts. Of course the caching would happen only in the case the key was not configured by the instance owner.

The current PR is my least favorite option, but at least it takes out the guess work of why an instance "keeps logging me out"

**Comment by unixfox** [comment]
I'm for introducing this breaking change but would prefer to show a warning message for a couple of weeks (2 weeks) everywhere before introducing the change. So that less people get "shocked" by this new change.

**Comment by unixfox** [comment]
Closing in favor of https://github.com/iv-org/invidious/issues/3854

**Pull request closed without merging**
